export interface CompactQuestion {
  i: number;
  q: string;
  c: string[];
  a: string;
  e: string;
  d: 'easy' | 'intermediate' | 'advanced';
  t: 'restatement' | 'comparison' | 'contrast' | 'cause_effect';
  ch: number;
  v: [string, string][];
}

export const chunk1: CompactQuestion[] = [
  // CHAPTER 1 (1 - 25)
  {
    i: 1,
    q: "She hadn't eaten all day, and by the time she got home she was ______.",
    c: ["blighted", "confutative", "ravenous", "ostentatious", "blissful"],
    a: "c",
    e: "Ravenous (adj.) means extremely hungry. The context clue is that she 'hadn't eaten all day', which naturally leads to being extremely hungry by the time she got home.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["ravenous", "Extremely hungry; voracious."], ["blighted", "Damaged, ruined, or suffering from a disease."], ["ostentatious", "Characterized by vulgar or pretentious display; designed to impress."]]
  },
  {
    i: 2,
    q: "The movie offended many of the parents of its younger viewers by including unnecessary ______ in the dialogue.",
    c: ["vulgarity", "verbosity", "vocalizations", "garishness", "tonality"],
    a: "a",
    e: "Vulgarity (n.) means offensive speech or conduct. The sentence indicates parents of younger viewers were offended by dialogue, which strongly suggests vulgarity.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["vulgarity", "Offensive or crude speech, writing, or behavior."], ["verbosity", "The quality of using more words than needed."], ["garishness", "Obtrusive bright or showy qualities."]]
  },
  {
    i: 3,
    q: "His neighbors found his ______ manner bossy and irritating, and they stopped inviting him to backyard barbeques.",
    c: ["insentient", "magisterial", "reparatory", "restorative", "modest"],
    a: "b",
    e: "Magisterial (adj.) means overbearing, domineering, or offensively self-assured. The sentence defines it directly as 'bossy and irritating.'",
    d: "easy",
    t: "restatement",
    ch: 1,
    v: [["magisterial", "Assertive, domineering, dictatorial, or overbearing."], ["insentient", "Incapable of feeling or understanding."], ["reparatory", "Serving to make amends or give satisfaction."]]
  },
  {
    i: 4,
    q: "Steven is always ______ about showing up for work because he feels that tardiness is a sign of irresponsibility.",
    c: ["legible", "tolerable", "punctual", "literal", "belligerent"],
    a: "c",
    e: "Punctual (adj.) means arriving exactly on time. Since Steven views tardiness (lateness) as irresponsible, he is sure to be punctual.",
    d: "easy",
    t: "contrast",
    ch: 1,
    v: [["punctual", "Happening or doing something at the agreed or proper time."], ["belligerent", "Hostile and aggressive; eager to fight."]]
  },
  {
    i: 5,
    q: "Candace would ______ her little sister into an argument by teasing her and calling her names.",
    c: ["advocate", "provoke", "perforate", "lamente", "expunge"],
    a: "b",
    e: "To provoke (v.) is to incite anger, resentment, or prompt an action. Teasing and calling names is meant to provoke an argument.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["provoke", "To stimulate, incite, or anger someone into active response."], ["expunge", "To obliterate or completely erase something from a record."]]
  },
  {
    i: 6,
    q: "The dress Ariel wore ______ with small, glassy beads, creating a shimmering effect.",
    c: ["abated", "absolved", "scintillated", "asserted", "bemoaned"],
    a: "c",
    e: "Scintillated (v.) means shined, sparkled, or flashed brightly. Visual beads causing a sparkling effect matches this definition.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["scintillate", "To emit flashes of light; sparkle."], ["abated", "Became less intense or widespread."]]
  },
  {
    i: 7,
    q: "Being able to afford this luxury car will ______ getting a better-paying job.",
    c: ["reiterate", "expatriate", "abdicate", "necessitate", "procrastinate"],
    a: "d",
    e: "Necessitate (v.) means to make necessary, require as prerequisite or logically force.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["necessitate", "Make something necessary as a result or consequence."], ["abdicate", "Renounce one's throne or official duty."]]
  },
  {
    i: 8,
    q: "Levina unknowingly ______ the thief by holding open the elevator doors and ensuring his escape.",
    c: ["coerced", "condoned", "abetted", "chastised", "balked"],
    a: "c",
    e: "To abet (v.) is to encourage, assist, or support someone, especially in wrongdoing.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["abet", "Encourage or assist someone to commit a crime."], ["chastise", "Rebuke or reprimand severely."]]
  },
  {
    i: 9,
    q: "Shakespeare, a ______ writer, entertained audiences by writing many tragic and comic plays.",
    c: ["generic", "sluggish", "pensive", "prolific", "frugal"],
    a: "d",
    e: "Prolific (adj.) means highly productive or producing abundant works. Writing many plays fits this concept.",
    d: "easy",
    t: "restatement",
    ch: 1,
    v: [["prolific", "Present in large numbers or producing much fruit or works."], ["frugal", "Sparing or economical as regards money or food."]]
  },
  {
    i: 10,
    q: "I had the ______ experience of sitting next to an over-talkative passenger on my flight home from Brussels.",
    c: ["gilded", "exquisite", "galling", "jovial", "serene"],
    a: "c",
    e: "Galling (adj.) means annoying, irritating, causing vexation or resentment.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["galling", "Annoying; humiliating."], ["jovial", "Cheerful and friendly."]]
  },
  {
    i: 11,
    q: "Prince Phillip had to choose: marry the woman he loved and ______ his right to the throne, or marry Lady Fiona.",
    c: ["congeal", "instigate", "abdicate", "assert", "enforce"],
    a: "c",
    e: "To abdicate (v.) is to formally give up a throne, high office, or sovereignty.",
    d: "easy",
    t: "contrast",
    ch: 1,
    v: [["abdicate", "Renounce one's throne or sovereign right."], ["instigate", "Bring about or initiate an action."]]
  },
  {
    i: 12,
    q: "If you will not do your work of your own ______, I have no choice but to penalize you.",
    c: ["demise", "compulsion", "extortion", "volition", "indifferency"],
    a: "d",
    e: "Volition (n.) means the power or act of using one's own will or choices.",
    d: "easy",
    t: "contrast",
    ch: 1,
    v: [["volition", "The faculty or power of using one's will."], ["compulsion", "The action of being forced to do something."]]
  },
  {
    i: 13,
    q: "After sitting in the sink for several days, the dirty, food-encrusted dishes became ______.",
    c: ["malodorous", "wholesome", "spotless", "fragrant", "arid"],
    a: "a",
    e: "Malodorous (adj.) means bad-smelling, decaying, or emitting foul odor.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["malodorous", "Smelling very unpleasant."], ["arid", "Having little or no rain; dry."]]
  },
  {
    i: 14,
    q: "Giulia soon discovered the source of the ______ smell in the room: a week-old tuna sandwich containing mold.",
    c: ["perfumed", "savory", "mild", "sterile", "fetid"],
    a: "e",
    e: "Fetid (adj.) means smelling extremely unpleasant, stinking, or rotten.",
    d: "easy",
    t: "restatement",
    ch: 1,
    v: [["fetid", "Smelling extremely unpleasant; stinking."], ["sterile", "Free from bacteria or microorganisms."]]
  },
  {
    i: 15,
    q: "After making ______ remarks to the President, the reporter was not invited back to the White House press room.",
    c: ["hospitable", "eminent", "deferential", "servile", "irreverent"],
    a: "e",
    e: "Irreverent (adj.) means showing a lack of respect for people or things that are generally taken seriously.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["irreverent", "Showing a lack of respect for people or things usually taken seriously."], ["deferential", "Showing respect or high esteem."]]
  },
  {
    i: 16,
    q: "With her ______ eyesight, Krystyna spotted a trio of deer on the hillside long before anyone else in the group.",
    c: ["bleary", "keen", "myopic", "distorted", "obscure"],
    a: "b",
    e: "Keen (adj.) means sharp, highly developed, or very sensitive.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["keen", "Highly developed; sharp."], ["myopic", "Nearsighted; short-sighted."]]
  },
  {
    i: 17,
    q: "With a ______ grin, the boy quickly slipped the candy into his pocket without paying.",
    c: ["innocent", "nefarious", "benevolent", "dull", "candid"],
    a: "b",
    e: "Nefarious (adj.) means wicked, evil, or criminal.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["nefarious", "Wicked or criminal."], ["candid", "Truthful and straightforward; frank."]]
  },
  {
    i: 18,
    q: "Her ______ display of tears at work left her coworkers feeling highly awkward and uncomfortable.",
    c: ["maudlin", "stoic", "subdued", "jovial", "indifferent"],
    a: "a",
    e: "Maudlin (adj.) means self-pityingly or tearfully sentimental, often in an exaggerated way.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["maudlin", "Tearfully sentimental or self-pitying."], ["stoic", "Enduring pain and hardship without showing feelings."]]
  },
  {
    i: 19,
    q: "Johan argued, 'If you know about a crime and do nothing, you are ______ in that crime.'",
    c: ["innocent", "ignorant", "unaware", "complicit", "exempt"],
    a: "d",
    e: "Complicit (adj.) means involved with others in an illegal activity or wrongdoing.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["complicit", "Involved with others in an illegal activity or wrongdoing."], ["exempt", "Free from an obligation or liability."]]
  },
  {
    i: 20,
    q: "The authorities, fearing a ______ of their power, called for a military state.",
    c: ["subversion", "support", "validation", "expansion", "reinforcement"],
    a: "a",
    e: "Subversion (n.) means the undermining or overthrow of power and authority.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["subversion", "The undermining of the power and authority of an established system."], ["validation", "The action of checking or proving the validity of something."]]
  },
  {
    i: 21,
    q: "The story's bitter antagonist felt such great ______ for all of the other characters that he wanted to ruin them.",
    c: ["benevolence", "malevolence", "apathy", "sympathy", "empathy"],
    a: "b",
    e: "Malevolence (n.) is the state or feeling of wishing to do evil to others.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["malevolence", "A desire to do evil to others."], ["benevolence", "Well meaning and kindly nature."]]
  },
  {
    i: 22,
    q: "It is difficult to believe that charging 20% on an outstanding credit card balance isn’t ______!",
    c: ["generosity", "usury", "charity", "frugality", "probity"],
    a: "b",
    e: "Usury (n.) is the illegal action or practice of lending money at unreasonably high rates of interest.",
    d: "easy",
    t: "restatement",
    ch: 1,
    v: [["usury", "The lending of money at unreasonably high interest rates."], ["probity", "The quality of having strong moral principles; honesty."]]
  },
  {
    i: 23,
    q: "The ______ weather patterns of the tropical island shifted rapidly from bright sun to pouring rain.",
    c: ["static", "monotonous", "bleak", "arid", "kaleidoscopic"],
    a: "e",
    e: "Kaleidoscopic (adj.) means rapidly changing, complex, or multicolored.",
    d: "easy",
    t: "restatement",
    ch: 1,
    v: [["kaleidoscopic", "Having rapidly changing, multicolored patterns or phases."], ["static", "Lacking in movement, action, or change."]]
  },
  {
    i: 24,
    q: "Wedding ceremonies often include the exchange of ______ rings to symbolize the couple’s promises to each other.",
    c: ["temporary", "illusory", "worthless", "transient", "votive"],
    a: "e",
    e: "Votive (adj.) means offered or consecrated in fulfillment of a vow.",
    d: "easy",
    t: "restatement",
    ch: 1,
    v: [["votive", "Expressing or symbolizing a vow or wish."], ["transient", "Lasting only for a short time; impermanent."]]
  },
  {
    i: 25,
    q: "Kym was ______ in choosing her friends, so her parties were attended by vastly different people who had little in common.",
    c: ["selective", "indiscriminate", "careful", "exclusives", "particular"],
    a: "b",
    e: "Indiscriminate (adj.) means done at random or without careful judgment/selectivity.",
    d: "easy",
    t: "cause_effect",
    ch: 1,
    v: [["indiscriminate", "Done at random or without careful distinction."], ["particular", "Very careful or selective about details."]]
  },

  // CHAPTER 2 (26 - 50)
  {
    i: 26,
    q: "Phillip’s ______ tone endeared him to his comical friends, but irritated his serious father.",
    c: ["aloof", "jesting", "grave", "earnest", "conservative"],
    a: "b",
    e: "Jesting (adj.) means playful, joking, or humorous. It contrasts with 'serious father' and aligns with 'comical friends'.",
    d: "easy",
    t: "contrast",
    ch: 2,
    v: [["jesting", "Playful, joking, or bantering in tone."], ["aloof", "Cool, distant, detached, or uninvolved."]]
  },
  {
    i: 27,
    q: "Brian’s pale Irish skin was ______ to burn if he spent too much time in the sun.",
    c: ["prone", "urbane", "eminent", "erect", "daunted"],
    a: "a",
    e: "Prone (adj.) means likely or susceptible to experience something.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["prone", "Susceptible, inclined, or vulnerable to something."], ["urbane", "Suave, courteous, and refined in manner."]]
  },
  {
    i: 28,
    q: "A fan of historical fiction, Joline is now reading a novel about slavery in the ______ South.",
    c: ["decorous", "rogue", "droll", "antebellum", "onerous"],
    a: "d",
    e: "Antebellum (adj.) means occurring or existing before a particular war, especially the American Civil War.",
    d: "easy",
    t: "restatement",
    ch: 2,
    v: [["antebellum", "Belonging to the period before the Civil War."], ["onerous", "Involving a heavy amount of effort or burden."]]
  },
  {
    i: 29,
    q: "Over the years the Wilsons slowly ______ upon the Jacksons’ property, moving the stone markers farther onto the Jacksons’ land.",
    c: ["encroached", "jettisoned", "conjoined", "repudiated", "teemed"],
    a: "a",
    e: "To encroach (v.) means to intrude on territory or rights gradually.",
    d: "easy",
    t: "restatement",
    ch: 2,
    v: [["encroach", "Intrude on a person's territory or rights gradually."], ["repudiate", "Refuse to accept or be associated with."]]
  },
  {
    i: 30,
    q: "Mary became ______ at typing because she practiced every day for six months.",
    c: ["proficient", "reflective", "dormant", "redundant", "valiant"],
    a: "a",
    e: "Proficient (adj.) means skilled, competent, or advanced in a branch of knowledge.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["proficient", "Competent, skilled, or highly expert."], ["dormant", "Temporarily inactive, asleep, or inoperative."]]
  },
  {
    i: 31,
    q: "To find out what her husband bought, Susan attempted to ______ his family members by asking strategic questions.",
    c: ["placate", "probe", "balk", "vouch", "evade"],
    a: "b",
    e: "To probe (v.) means to physically explore or examine with a tool or inquire closely.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["probe", "Inquire into or closely investigate."], ["placate", "Make someone less angry or hostile."]]
  },
  {
    i: 32,
    q: "Juan's friends found him in a ______ mood after he learned he was selected for the role.",
    c: ["jovial", "melancholy", "somber", "subdued", "indifferent"],
    a: "a",
    e: "Jovial (adj.) means cheerful, friendly, and celebratory.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["jovial", "Cheerful and friendly."], ["melancholy", "A feeling of pensive sadness."]]
  },
  {
    i: 33,
    q: "His heavy steel suit of armor made the knight ______ to his enemy's sword blow.",
    c: ["susceptible", "fragile", "invulnerable", "vulnerable", "exposed"],
    a: "c",
    e: "Invulnerable (adj.) means impossible to harm or damage.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["invulnerable", "Impossible to harm or damage."], ["susceptible", "Likely to be influenced or harmed by a particular thing."]]
  },
  {
    i: 34,
    q: "Choosing a small, fuel-efficient car is a ______ purchase for a student on a small budget.",
    c: ["reckless", "frivolous", "precarious", "audacious", "judicious"],
    a: "e",
    e: "Judicious (adj.) means having, showing, or done with good judgment or sense.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["judicious", "Having or showing good judgment."], ["precarious", "Not securely held or position; unsafe."]]
  },
  {
    i: 35,
    q: "Such a ______ violation of school policy will certainly result in a suspension.",
    c: ["subtle", "flagrant", "discrete", "unconscious", "minor"],
    a: "b",
    e: "Flagrant (adj.) means of an action considered wrong or offensive, obviously and conspicuously offensive.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["flagrant", "Conspicuously or obviously offensive."], ["discrete", "Individually separate and distinct."]]
  },
  {
    i: 36,
    q: "With all of the recent negative events, she felt ______ forces must be at work in her life.",
    c: ["benevolent", "propitious", "malignant", "salutary", "wholesome"],
    a: "c",
    e: "Malignant (adj.) means malevolent, hostile, or infectious with evil or illness.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["malignant", "Malevolent; evil or cancerous."], ["salutary", "Producing good effects; beneficial."]]
  },
  {
    i: 37,
    q: "The ______ rumors about her personal life did a great deal of damage to her public reputation.",
    c: ["verified", "authentic", "apocryphal", "factual", "laudable"],
    a: "c",
    e: "Apocryphal (adj.) means of a story or rumor of doubtful authenticity, although widely circulated as true.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["apocryphal", "Of doubtful authenticity; fictitious."], ["laudable", "Deserving praise and commendation."]]
  },
  {
    i: 38,
    q: "Pam had a persistent tendency to ______ and delay, which always put her further behind in her schedule.",
    c: ["expedite", "precipitate", "advance", "accelerate", "procrastinate"],
    a: "e",
    e: "Procrastinate (v.) means to delay or postpone action; put off doing something.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["procrastinate", "Delay or postpone action; put off."], ["expedite", "Make an action happen sooner."]]
  },
  {
    i: 39,
    q: "Racha's silent glance was a ______ invitation to speak, which I immediately accepted.",
    c: ["vocal", "express", "flagrant", "tacit", "unwelcome"],
    a: "d",
    e: "Tacit (adj.) means understood or implied without being directly stated in spoken words.",
    d: "easy",
    t: "restatement",
    ch: 2,
    v: [["tacit", "Implied without being directly stated."], ["vocal", "Expressed with the voice."]]
  },
  {
    i: 40,
    q: "She reached the ______ of her career with her fourth novel, which won the Pulitzer Prize.",
    c: ["nadir", "apogee", "abyss", "base", "trough"],
    a: "b",
    e: "Apogee (n.) means the highest point in the development of something; climax or peak.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["apogee", "The highest point; peak."], ["nadir", "The lowest point of a situation."]]
  },
  {
    i: 41,
    q: "The ______ townspeople celebrated their team's championship well into the night.",
    c: ["glum", "indifferent", "jubilant", "apathetic", "critical"],
    a: "c",
    e: "Jubilant (adj.) means feeling or expressing great happiness and triumph.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["jubilant", "Feeling or expressing great joy or triumph."], ["glum", "Looking or feeling dejected or morose."]]
  },
  {
    i: 42,
    q: "The governor-elect was continuously hounded by a group of ______ lobbyists looking for favors.",
    c: ["critical", "hostile", "impartial", "fawning", "disinterested"],
    a: "d",
    e: "Fawning (adj.) means displaying exaggerated flattery or affection; obsequious.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["fawning", "Exaggerating affection; obsequious."], ["impartial", "Treating all rivals or disputants equally."]]
  },
  {
    i: 43,
    q: "The mock graduation ceremony was a complete ______ that offended the faculty and administration.",
    c: ["masterpiece", "tribute", "celebration", "travesty", "validation"],
    a: "d",
    e: "A travesty (n.) is a false, absurd, or distorted representation of something.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["travesty", "A distorted, absurd, or false representation."], ["tribute", "An act, statement, or gift loved to show respect."]]
  },
  {
    i: 44,
    q: "The busy, ______ fabric of the clown's tie clashed horribly with his polka-dot shirt.",
    c: ["mottled", "uniform", "plain", "drab", "muted"],
    a: "a",
    e: "Mottled (adj.) means marked with spots or colored patches; blotchy.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["mottled", "Blotchy; spotted with colors."], ["uniform", "Remaining the same in all cases and times."]]
  },
  {
    i: 45,
    q: "Kendrick's piano talent flourished under the expert ______ of his world-class mentor.",
    c: ["opposition", "neglect", "tutelage", "ignorance", "derision"],
    a: "c",
    e: "Tutelage (n.) means protection of or authority over someone or something; guardianship or instruction.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["tutelage", "Guardianship, instruction, or expert guidance."], ["derision", "Contemptuous ridicule or mockery."]]
  },
  {
    i: 46,
    q: "The children were ______ by the seemingly nonsensical clues left in the scavenger hunt.",
    c: ["enlightened", "clarified", "comforted", "pacified", "flummoxed"],
    a: "e",
    e: "Flummoxed (adj.) means bewildered, perplexed, or completely confused.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["flummoxed", "Perplexed or utterly bewildered."], ["clarified", "Made less confused and more comprehensible."]]
  },
  {
    i: 47,
    q: "As the protagonist in Romeo and Juliet, Romeo is a ______ but tragic figure.",
    c: ["hero", "villain", "spectator", "bystander", "informant"],
    a: "a",
    e: "The protagonist is the leading character or hero in a drama.",
    d: "easy",
    t: "restatement",
    ch: 2,
    v: [["hero", "The noble protagonist."], ["villain", "A character whose evil actions plot the drama."]]
  },
  {
    i: 48,
    q: "The chess master promised to ______ havoc on his opponent's defenses during the match.",
    c: ["wreak", "prevent", "ameliorate", "stifle", "mitigate"],
    a: "a",
    e: "To wreak (v.) means to cause or inflict a large amount of damage or harm.",
    d: "easy",
    t: "cause_effect",
    ch: 2,
    v: [["wreak", "Inflict or cause damage/harm."], ["mitigate", "Make less severe, serious, or painful."]]
  },
  {
    i: 49,
    q: "I have always admired Seymour's ______; I've never seen him ruffled, even under extreme pressure.",
    c: ["aplomb", "cowardice", "anxiety", "indecision", "timidity"],
    a: "a",
    e: "Aplomb (n.) means self-confidence or assurance, especially when in a demanding situation.",
    d: "easy",
    t: "restatement",
    ch: 2,
    v: [["aplomb", "Poise, self-confidence, or composure."], ["timidity", "Lack of courage or confidence."]]
  },
  {
    i: 50,
    q: "The soldiers received a military ______ to inspect all incoming vehicles at the border crossing.",
    c: ["suggestion", "query", "request", "plea", "mandate"],
    a: "e",
    e: "A mandate (n.) is an official order or commission to do something.",
    d: "easy",
    t: "restatement",
    ch: 2,
    v: [["mandate", "An official order or command."], ["query", "A question, especially one expressing doubt."]]
  },

  // CHAPTER 3 (51 - 75)
  {
    i: 51,
    q: "As ______ beings we live each day conscious of our shortcomings and victories.",
    c: ["sensational", "sentient", "sentimental", "static", "senile"],
    a: "b",
    e: "Sentient (adj.) means possessing the power of sense perception; conscious, aware, or capable of feeling.",
    d: "intermediate",
    t: "restatement",
    ch: 3,
    v: [["sentient", "Able to perceive or feel things; conscious."], ["senile", "Showing cognitive decline due to old age."]]
  },
  {
    i: 52,
    q: "The curious crowd gathered to watch the irate customer ______ about the poor service he received.",
    c: ["antiquate", "trivialize", "rant", "placate", "fetter"],
    a: "c",
    e: "To rant (v.) means to speak loudly, violently, or wildly under anger.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["rant", "To shout or speak in an angry, impassioned way."], ["placate", "To appease or pacify someone."]]
  },
  {
    i: 53,
    q: "The man’s ______ driving resulted in a four-car pile-up on the freeway.",
    c: ["burdensome", "charismatic", "exceptional", "boastful", "negligent"],
    a: "e",
    e: "Negligent (adj.) means to habitually lack proper care or attention; careless.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["negligent", "Failing to take proper care; careless."]]
  },
  {
    i: 54,
    q: "At that critical ______ in the championship game, the coach called a crucial timeout.",
    c: ["milieu", "oasis", "juncture", "hiatus", "latency"],
    a: "c",
    e: "A juncture (n.) is a particular point in events or time, especially a critical one.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["juncture", "A critical point of time or joint."], ["hiatus", "A temporary pause or gap."]]
  },
  {
    i: 55,
    q: "My ancestor who lost his life in the Revolutionary War was a ______ for American independence.",
    c: ["knave", "reactionary", "compatriot", "nonconformist", "martyr"],
    a: "e",
    e: "A martyr (n.) is someone who sacrifices life for a vital cause or principle.",
    d: "intermediate",
    t: "restatement",
    ch: 3,
    v: [["martyr", "A person killed because of beliefs or a noble cause."]]
  },
  {
    i: 56,
    q: "The ______ sound of the radiator as it released hot steam terrified the sleeping cat.",
    c: ["sibilant", "mellifluous", "resonant", "cacophonous", "silent"],
    a: "a",
    e: "Sibilant (adj.) means characterized by a hissing sound.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["sibilant", "Making or having a hissing sound."], ["mellifluous", "Sweet or musical; pleasant to hear."]]
  },
  {
    i: 57,
    q: "It is helpful for salesmen to develop a good ______ with their customers in order to gain their trust.",
    c: ["platitude", "rapport", "ire", "tribute", "disinclination"],
    a: "b",
    e: "A rapport (n.) is a relationship built on mutual harmony, understanding, or trust.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["rapport", "A harmonious relationship based on trust."], ["platitude", "A moral statement used too often to be interesting."]]
  },
  {
    i: 58,
    q: "As director of operations, he had ______ responsibilities that required a wide variety of skills.",
    c: ["scanty", "trivial", "insignificant", "manifold", "singular"],
    a: "d",
    e: "Manifold (adj.) means many and various; diverse or multifaceted.",
    d: "intermediate",
    t: "restatement",
    ch: 3,
    v: [["manifold", "Many and various; diverse."], ["scanty", "Small or insufficient in quantity."]]
  },
  {
    i: 59,
    q: "David's ______ entrance on stage disrupted the actors mid-scene and regular run of the play.",
    c: ["untimely", "impeccable", "fitting", "anticipated", "calculated"],
    a: "a",
    e: "Untimely (adj.) means occurring at an unsuitable, premature, or unfortunate time.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["untimely", "Happening or done at an unsuitable time."], ["impeccable", "In accordance with the highest standards; faultless."]]
  },
  {
    i: 60,
    q: "The valley contains plenty of ______ land that is perfect for growing crops and farming.",
    c: ["barren", "arid", "arable", "desolate", "boggy"],
    a: "c",
    e: "Arable (adj.) means suitable for growing crops or farming.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["arable", "Suitable for farming or growing crops."], ["barren", "Too poor to produce vegetation."]]
  },
  {
    i: 61,
    q: "The ______ seventh-grader towered over his classmates and regularly tripped over his own feet.",
    c: ["gangling", "diminutive", "compact", "robust", "muscular"],
    a: "a",
    e: "Gangling (adj.) means tall, thin, and moving awkwardly.",
    d: "intermediate",
    t: "restatement",
    ch: 3,
    v: [["gangling", "Tall, thin, and awkward in movement."], ["diminutive", "Extremely or unusually small."]]
  },
  {
    i: 62,
    q: "Carson was at first flattered by the excessive ______ of his new associates, but soon grew suspicious of their motives.",
    c: ["criticism", "adulation", "neglect", "derision", "probing"],
    a: "b",
    e: "Adulation (n.) is obsequious flattery or excessive admiration/praise.",
    d: "intermediate",
    t: "contrast",
    ch: 3,
    v: [["adulation", "Excessive praise or flattery."], ["derision", "Sarcastic mockery or ridicule."]]
  },
  {
    i: 63,
    q: "For a ______ fee, it is possible to upgrade your ticket to premium seating.",
    c: ["nominal", "exorbitant", "prohibitive", "ruinous", "extravagant"],
    a: "a",
    e: "Nominal (adj.) means of a price, charge, or fee, very small or far below the real value.",
    d: "intermediate",
    t: "contrast",
    ch: 3,
    v: [["nominal", "Exist in name only; very small price."], ["exorbitant", "Price unreasonably high."]]
  },
  {
    i: 64,
    q: "Leaving through the back window, the thieves proceeded to ______ the entire house looking for hidden cash.",
    c: ["renovate", "safeguard", "decorate", "ransack", "beautify"],
    a: "d",
    e: "To ransack (v.) means to go through a place stealing things and causing damage.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["ransack", "Search thoroughly, stealing and destroying."], ["renovate", "Restore to a good state of repair."]]
  },
  {
    i: 65,
    q: "The ______ deer stuck close to its mother as they crossed the open forest meadow.",
    c: ["elderly", "ancient", "yearling", "predatory", "nocturnal"],
    a: "c",
    e: "A yearling (n.) is an animal, especially a deer or horse, that is one year old.",
    d: "intermediate",
    t: "restatement",
    ch: 3,
    v: [["yearling", "An animal next in age to its birth-year."]]
  },
  {
    i: 66,
    q: "To ______ his educational goals, James designed a highly meticulous weekly library schedule.",
    c: ["abridge", "thwart", "effectuate", "lament", "deride"],
    a: "c",
    e: "To effectuate (v.) means to bring about, put into operation, or successfully achieve.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["effectuate", "Put into force or achieve."], ["abridge", "Shorten a book or writing."]]
  },
  {
    i: 67,
    q: "The defense attorney argued that the unsigned contract was legally ______ and had no force.",
    c: ["binding", "void", "valid", "salutary", "judicious"],
    a: "b",
    e: "Void (adj.) means not valid, null, or having no legal force.",
    d: "intermediate",
    t: "restatement",
    ch: 3,
    v: [["void", "Null; having no binding force."], ["binding", "Legally requiring fulfillment."]]
  },
  {
    i: 68,
    q: "Although normally very loquacious, during the press event the CEO was unusually ______.",
    c: ["verbose", "garrulous", "taciturn", "articulate", "voluble"],
    a: "c",
    e: "Taciturn (adj.) means reserved, uncommunicative, or saying very little.",
    d: "intermediate",
    t: "contrast",
    ch: 3,
    v: [["taciturn", "Reserved or uncommunicative in speech."], ["garrulous", "Excessive talkative on trivial matters."]]
  },
  {
    i: 69,
    q: "The sudden morning blizzard ______ their long-awaited travel plans for the weekend ski retreat.",
    c: ["thwarted", "expedited", "boosted", "ratified", "abetted"],
    a: "a",
    e: "To thwart (v.) means to prevent someone or something from accomplishing their purpose.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["thwart", "Oppose successfully; prevent plans."], ["expedite", "Speed up progress."]]
  },
  {
    i: 70,
    q: "After several days of heavy rain, the topsoil became completely ______ with water.",
    c: ["parched", "desiccated", "saturated", "arid", "sterile"],
    a: "c",
    e: "Saturated (adj.) means thoroughly soaked, holding as much moisture as can be absorbed.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["saturated", "Soaked; thoroughly wet."], ["desiccated", "Completely dried out."]]
  },
  {
    i: 71,
    q: "The exotic blend of garlic and herbs made the chef's specialty incredibly ______.",
    c: ["insipid", "savory", "unpalatable", "bland", "fetid"],
    a: "b",
    e: "Savory (adj.) means belonging to the category of salty or spicy rather than sweet; appetizing.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["savory", "Appetizing; spicy or salty taste."], ["insipid", "Lacking flavor; weak or tasteless."]]
  },
  {
    i: 72,
    q: "The kind nurse tried to ______ the crying child's fear by blowing bubbles.",
    c: ["exacerbate", "provoke", "allay", "prolong", "foster"],
    a: "c",
    e: "To allay (v.) means to diminish or put at rest, especially fear or suspicion.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["allay", "Diminish or quiet fear/worry."], ["exacerbate", "Make a bad situation worse."]]
  },
  {
    i: 73,
    q: "In the dry desert environment, potable water is a ______ resource that is strictly rationed.",
    c: ["sparse", "plentiful", "abundant", "teeming", "profuse"],
    a: "a",
    e: "Sparse (adj.) means thinly dispersed or scattered; insufficient in number or quantity.",
    d: "intermediate",
    t: "restatement",
    ch: 3,
    v: [["sparse", "Scantily scattered; thin."], ["profuse", "Extravagantly abundant."]]
  },
  {
    i: 74,
    q: "With her ______ memory, she was able to memorize entire pages of poetry in single readings.",
    c: ["flaccid", "tenacious", "bleary", "erratic", "senile"],
    a: "b",
    e: "Tenacious (adj.) means keeping a firm hold, persisting, or highly retentive.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["tenacious", "Firmly holding or highly retentive."], ["flaccid", "Lacking firmness or force."]]
  },
  {
    i: 75,
    q: "The stone fortress on the coast stands as a ______ landmark that has withstood centuries of hurricane winds.",
    c: ["transient", "durable", "temporary", "fragile", "subverted"],
    a: "b",
    e: "Durable (adj.) means able to withstand wear, pressure, or damage over a long period.",
    d: "intermediate",
    t: "cause_effect",
    ch: 3,
    v: [["durable", "Hard-wearing and long-lasting."], ["transient", "Passing through quickly."]]
  },

  // CHAPTER 4 (76 - 100)
  {
    i: 76,
    q: "Zachary was doomed to a miserable life, for no matter how much he had, he always ______ the possessions of others.",
    c: ["protracted", "exalted", "engendered", "coveted", "filibustered"],
    a: "d",
    e: "To covet (v.) is to wish or long for; to feel immoderate desire for that which belongs to another.",
    d: "intermediate",
    t: "cause_effect",
    ch: 4,
    v: [["covet", "To yearn to possess or have something belonging to someone else."]]
  },
  {
    i: 77,
    q: "Sheila’s grueling hike included passing through numerous vertical ______.",
    c: ["terrariums", "neoprene", "jurisdictions", "ravines", "belfries"],
    a: "d",
    e: "A ravine (n.) is a deep narrow canyon or gorge.",
    d: "intermediate",
    t: "restatement",
    ch: 4,
    v: [["ravines", "Deep, narrow gorges with steep sides."]]
  },
  {
    i: 78,
    q: "The college professor was known on campus as a ______ character—bland but harmless and noble.",
    c: ["staid", "stagnant", "auspicious", "sterile", "dogmatic"],
    a: "a",
    e: "Staid (adj.) means of a steady, sober, serious, and colorless character.",
    d: "intermediate",
    t: "restatement",
    ch: 4,
    v: [["staid", "Sedate, respectable, and unadventurous; colorless."]]
  },
  {
    i: 79,
    q: "Because he was so ______ , the athlete completed the obstacle course in record time.",
    c: ["belligerent", "nimble", "demure", "volatile", "speculative"],
    a: "b",
    e: "Nimble (adj.) means quick and light in movement; agile and responsive.",
    d: "easy",
    t: "cause_effect",
    ch: 4,
    v: [["nimble", "Quick and light in movement or action; agile."]]
  },
  {
    i: 80,
    q: "The toy store’s extensive inventory offered a ______ of toys from baby items to video games.",
    c: ["manifold", "lexicon", "burrow", "gamut", "motif"],
    a: "d",
    e: "A gamut (n.) is an entire range or a whole series.",
    d: "intermediate",
    t: "restatement",
    ch: 4,
    v: [["gamut", "The complete range or scope of something."]]
  },
  {
    i: 81,
    q: "Although the storm was intense, it was ______ and cleared within twenty minutes.",
    c: ["perpetual", "transient", "interminable", "stagnant", "chronic"],
    a: "b",
    e: "Transient (adj.) means lasting only for a short time; impermanent.",
    d: "easy",
    t: "contrast",
    ch: 4,
    v: [["transient", "Passing quickly; short-lived."], ["interminable", "Endless; excessively long."]]
  },
  {
    i: 82,
    q: "The speaker's ______ and unclear explanations left the audience highly confused.",
    c: ["lucid", "convoluted", "articulate", "transparent", "fidgety"],
    a: "b",
    e: "Convoluted (adj.) means extremely complex and difficult to follow.",
    d: "intermediate",
    t: "cause_effect",
    ch: 4,
    v: [["convoluted", "Intricate and complex; difficult."], ["lucid", "Expressed clearly; easy to understand."]]
  },
  {
    i: 83,
    q: "Unlike his frugal brother who saved every penny, Julian was ______ and spent his savings on luxuries.",
    c: ["niggardly", "frugal", "covetous", "profligate", "parsimonious"],
    a: "d",
    e: "Profligate (adj.) means recklessly extravagant or wasteful in resources.",
    d: "advanced",
    t: "contrast",
    ch: 4,
    v: [["profligate", "Recklessly extravagant or wasteful."], ["parsimonious", "Unwilling to spend money; frugal."]]
  },
  {
    i: 84,
    q: "The primary purpose of the insurance policy is to ______ the homeowner against natural disasters.",
    c: ["liquidate", "jeopardize", "indemnify", "subvert", "penalize"],
    a: "c",
    e: "To indemnify (v.) means to compensate someone for harm or loss, or secure against legal liability.",
    d: "advanced",
    t: "cause_effect",
    ch: 4,
    v: [["indemnify", "Guarantee against loss; compensate."], ["liquidate", "Wind up the affairs of a business."]]
  },
  {
    i: 85,
    q: "Despite the high-stress environment, the emergency surgeon maintained absolute ______ throughout.",
    c: ["composure", "hysteria", "fluctuation", "indecision", "trepidation"],
    a: "a",
    e: "Composure (n.) is the state or feeling of being calm and in control of oneself.",
    d: "easy",
    t: "contrast",
    ch: 4,
    v: [["composure", "The state of being calm and balanced."], ["trepidation", "A feeling of fear or agitation about something."]]
  },
  {
    i: 86,
    q: "The continuous rainfall has caused the local river's water levels to ______ significantly.",
    c: ["dwindle", "fluctuate", "stabilize", "escalate", "evaporate"],
    a: "d",
    e: "Escalate (v.) means to increase rapidly or intensity.",
    d: "easy",
    t: "cause_effect",
    ch: 4,
    v: [["escalate", "Increase rapidly; rise."], ["dwindle", "Diminish gradually in size or strength."]]
  },
  {
    i: 87,
    q: "His argument was entirely ______ , lacking any concrete evidence or logical organization.",
    c: ["validated", "coherent", "specious", "impeccable", "persuasive"],
    a: "c",
    e: "Specious (adj.) means superficially plausible, but actually wrong or misleading.",
    d: "intermediate",
    t: "restatement",
    ch: 4,
    v: [["specious", "Superficially true but actually false."], ["coherent", "Logical and consistent; unified."]]
  },
  {
    i: 88,
    q: "The newly discovered documentation serves to ______ the claim that the artwork is a forgery.",
    c: ["invalidate", "substantiate", "disclaim", "contest", "subvert"],
    a: "b",
    e: "Substantiate (v.) means to provide evidence to support or prove the truth of.",
    d: "intermediate",
    t: "cause_effect",
    ch: 4,
    v: [["substantiate", "Support with proof or evidence."], ["invalidate", "Make illogical or legally inactive."]]
  },
  {
    i: 89,
    q: "The children were so ______ after playing in the hot sun all day that they fell asleep on the ride home.",
    c: ["vibrant", "energetic", "slack", "somnolent", "insentient"],
    a: "d",
    e: "Somnolent (adj.) means sleepy or drowsy.",
    d: "intermediate",
    t: "cause_effect",
    ch: 4,
    v: [["somnolent", "Sleepy or drowsy."], ["vibrant", "Full of energy and enthusiasm."]]
  },
  {
    i: 90,
    q: "The historical museum contains many artifacts representing the ______ culture of the early settlers.",
    c: ["contemporary", "indigenous", "nomadic", "futuristic", "imported"],
    a: "b",
    e: "Indigenous (adj.) means originating or occurring naturally in a particular place; native.",
    d: "easy",
    t: "restatement",
    ch: 4,
    v: [["indigenous", "Originating naturally in a region; native."], ["contemporary", "Living or occurring at the same time."]]
  },
  {
    i: 91,
    q: "In contrast to his sister’s cheerfulness, Marcus’s personality is generally ______.",
    c: ["ebullient", "morose", "jubilant", "gregarious", "vivacious"],
    a: "b",
    e: "Morose (adj.) means sullen and ill-tempered.",
    d: "easy",
    t: "contrast",
    ch: 4,
    v: [["morose", "Sullen; ill-tempered."], ["ebullient", "Cheerful and full of energy."]]
  },
  {
    i: 92,
    q: "Because she had a reputation for absolute ______ , everyone believed Jane’s account of the incident.",
    c: ["guile", "mendacity", "veracity", "cupidity", "artifice"],
    a: "c",
    e: "Veracity (n.) is conformity to facts; accuracy or truthfulness.",
    d: "intermediate",
    t: "cause_effect",
    ch: 4,
    v: [["veracity", "Truthfulness; accuracy."], ["mendacity", "Untruthfulness; lying."]]
  },
  {
    i: 93,
    q: "The mountain pass was so ______ that many hikers turned back due to safety concerns.",
    c: ["arable", "level", "precarious", "pliant", "hospitable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously likely to fall or collapse.",
    d: "easy",
    t: "cause_effect",
    ch: 4,
    v: [["precarious", "Unsafe; dangerously unstable."], ["pliant", "Easily bent; flexible."]]
  },
  {
    i: 94,
    q: "Rather than providing a useful response, the spokesperson gave a ______ answer that avoided the issue.",
    c: ["direct", "lucid", "definitive", "evasive", "candid"],
    a: "d",
    e: "Evasive (adj.) means tending to avoid commitment or self-revelation, especially by responding indirectly.",
    d: "easy",
    t: "contrast",
    ch: 4,
    v: [["evasive", "Avoiding direct answers; elusive."], ["candid", "Honest and straightforward."]]
  },
  {
    i: 95,
    q: "The business fell into bankruptcy due to the managers’ ______ financial investments.",
    c: ["frugal", "prudent", "provident", "imprudent", "conservative"],
    a: "d",
    e: "Imprudent (adj.) means not showing care for the consequences of an action; rash.",
    d: "easy",
    t: "cause_effect",
    ch: 4,
    v: [["imprudent", "Rash; not wise or cautious."], ["provident", "Making timely preparations for the future."]]
  },
  {
    i: 96,
    q: "The judge was praised for her ______ rulings, as she never allowed personal biases to influence her decisions.",
    c: ["biased", "partial", "equitable", "arbitrary", "subjective"],
    a: "c",
    e: "Equitable (adj.) means fair and impartial.",
    d: "intermediate",
    t: "cause_effect",
    ch: 4,
    v: [["equitable", "Fair and impartial."], ["arbitrary", "Based on random choice or whim."]]
  },
  {
    i: 97,
    q: "The software's interface was so ______ that even complete novices could master it in minutes.",
    c: ["obscure", "intuitive", "convoluted", "abstruse", "enigmatic"],
    a: "b",
    e: "Intuitive (adj.) means easy to use and understand without explicit instruction.",
    d: "easy",
    t: "cause_effect",
    ch: 4,
    v: [["intuitive", "Easy to understand immediately."], ["abstruse", "Difficult to understand; obscure."]]
  },
  {
    i: 98,
    q: "His speeches were filled with empty ______ that added nothing of substance to the debate.",
    c: ["wisdom", "rhetoric", "coherence", "clarity", "brevity"],
    a: "b",
    e: "Rhetoric (n.) is language designed to have a persuasive or impressive effect, but which is often regarded as lacking in sincerity or meaningful content.",
    d: "intermediate",
    t: "restatement",
    ch: 4,
    v: [["rhetoric", "Persuasive language lacking real substance."], ["brevity", "Concise and exact use of words."]]
  },
  {
    i: 99,
    q: "The continuous dry winds caused the lake to ______ and contract in size.",
    c: ["overflow", "expand", "subside", "saturate", "oscillate"],
    a: "c",
    e: "Subside (v.) means to go down to a lower or less normal level; sink, settle, or diminish.",
    d: "intermediate",
    t: "cause_effect",
    ch: 4,
    v: [["subside", "Sink or settle down; decrease."], ["oscillate", "Move or swing back and forth."]]
  },
  {
    i: 100,
    q: "The young apprentice was so ______ that she quickly mastered the complex trade secrets.",
    c: ["obtuse", "indolent", "apt", "negligent", "sluggish"],
    a: "c",
    e: "Apt (adj.) means having a natural tendency or highly quick to learn.",
    d: "easy",
    t: "cause_effect",
    ch: 4,
    v: [["apt", "Quick to learn; suited."], ["indolent", "Wanting to avoid activity; lazy."]]
  }
];
