import { CompactQuestion } from './sc_chunk_1';

export const chunk5: CompactQuestion[] = [
  // CHAPTER 17 (401 - 425)
  {
    i: 401,
    q: "Although initially thought to be benign, the growth turned out to be ______ , requiring immediate surgery.",
    c: ["salutary", "malignant", "harmless", "wholesome", "beneficial"],
    a: "b",
    e: "Malignant (adj.) means malevolent, harmful, or cancerous, which directly contrasts with benign (harmless).",
    d: "easy",
    t: "contrast",
    ch: 17,
    v: [["malignant", "Malevolent; harmful or cancerous."], ["benign", "Gentle and kindly; not harmful."]]
  },
  {
    i: 402,
    q: "Her highly emotional and ______ nature made it difficult for her friends to predict her reactions.",
    c: ["stable", "equable", "volatile", "constant", "tranquil"],
    a: "c",
    e: "Volatile (adj.) means liable to change rapidly and unpredictably, especially for the worse.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["volatile", "Liable to change rapidly and unpredictably."]]
  },
  {
    i: 403,
    q: "The old storyteller was incredibly ______ , talking for hours about his youth in rural Ohio.",
    c: ["garrulous", "laconic", "taciturn", "silent", "reserved"],
    a: "a",
    e: "Garrulous (adj.) means excessively talkative, especially on trivial matters.",
    d: "intermediate",
    t: "restatement",
    ch: 17,
    v: [["garrulous", "Excessively talkative on trivial matters."], ["laconic", "Using very few words."]]
  },
  {
    i: 404,
    q: "Unlike his wordy colleague, the manager's responses were highly ______ and directly to the point.",
    c: ["verbose", "garrulous", "laconic", "discursive", "rambling"],
    a: "c",
    e: "Laconic (adj.) of a person, speech, or style of writing, using very few words.",
    d: "intermediate",
    t: "contrast",
    ch: 17,
    v: [["laconic", "Using very few words; brief."], ["verbose", "Using more words than needed."]]
  },
  {
    i: 405,
    q: "Faced with a short deadline, the developers took a ______ approach, focusing only on core functions.",
    c: ["idealistic", "visionary", "pragmatic", "abstract", "speculative"],
    a: "c",
    e: "Pragmatic (adj.) means dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["pragmatic", "Practical rather than theoretical."]]
  },
  {
    i: 406,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 407,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 408,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 17,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 409,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 410,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 411,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 412,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 17,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 413,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 17,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 414,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 415,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 416,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 417,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 17,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 418,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 419,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 420,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 421,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 422,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 423,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 17,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 424,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 17,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 425,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 17,
    v: [["divergent", "Developing in different directions."]]
  },

  // CHAPTER 18 (426 - 450)
  {
    i: 426,
    q: "The ______ behavior of the fawning staff at the high-end hotel was intended to secure substantial tips.",
    c: ["insolent", "independent", "obsequious", "arrogant", "defiant"],
    a: "c",
    e: "Obsequious (adj.) means obedient or attentive to an excessive or servile degree.",
    d: "advanced",
    t: "cause_effect",
    ch: 18,
    v: [["obsequious", "Servile; excessively attentive/fawning."]]
  },
  {
    i: 427,
    q: "Celebrity fame is often ______ , disappearing as quickly as it originally arrived.",
    c: ["perpetual", "ephemeral", "interminable", "chronic", "lasting"],
    a: "b",
    e: "Ephemeral (adj.) means lasting for a very short time.",
    d: "intermediate",
    t: "contrast",
    ch: 18,
    v: [["ephemeral", "Lasting for a very short time; transient."]]
  },
  {
    i: 428,
    q: "To fit the guidelines of the journal, the author had to ______ his lengthy article.",
    c: ["expand", "abridge", "prolong", "lengthen", "elaborate"],
    a: "b",
    e: "To abridge (v.) means to shorten a book, movie, speech, or text without losing its main essence.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["abridge", "Shorten text without losing sense."]]
  },
  {
    i: 429,
    q: "His ______ behavior at the formal dinner surprised everyone who knew him as standardly polite.",
    c: ["aberrant", "decorous", "prudent", "orthodox", "mindful"],
    a: "a",
    e: "Aberrant (adj.) means departing from an accepted or normal standard.",
    d: "advanced",
    t: "contrast",
    ch: 18,
    v: [["aberrant", "Departing from accepted/normal standards."]]
  },
  {
    i: 430,
    q: "A strange ______ in the computer code caused the program to crash repeatedly during testing.",
    c: ["redundancy", "consistency", "anomaly", "validation", "logic"],
    a: "c",
    e: "An anomaly (n.) is something that deviates from what is standard, normal, or expected.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["anomaly", "Deviates from standard or normal."]]
  },
  {
    i: 431,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 432,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 433,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 18,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 434,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 435,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 436,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 437,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 18,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 438,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 18,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 439,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 440,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 441,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 442,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 18,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 443,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 444,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 445,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 446,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 447,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 448,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 18,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 449,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 18,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 450,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 18,
    v: [["divergent", "Developing in different directions."]]
  },

  // CHAPTER 19 (451 - 475)
  {
    i: 451,
    q: "The sudden morning ______ of car horns and sirens woke everyone in the urban apartment complex.",
    c: ["harmony", "symphony", "silence", "cacophony", "applause"],
    a: "d",
    e: "A cacophony (n.) is a harsh, discordant mixture of sounds.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["cacophony", "A harsh, discordant mixture of sounds."]]
  },
  {
    i: 452,
    q: "Smartphones have become completely ______ , used by almost everyone everywhere in modern society.",
    c: ["scarce", "ubiquitous", "extinct", "rare", "hidden"],
    a: "b",
    e: "Ubiquitous (adj.) means present, appearing, or found everywhere.",
    d: "easy",
    t: "restatement",
    ch: 19,
    v: [["ubiquitous", "Present, appearing, or found everywhere."]]
  },
  {
    i: 453,
    q: "Their massive, gilded mansion was viewed as highly ______ by their standard-income neighbors.",
    c: ["modest", "plain", "ostentatious", "frugal", "humble"],
    a: "c",
    e: "Ostentatious (adj.) means characterized by vulgar or pretentious display, designed to impress or attract notice.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["ostentatious", "Pretentious display to attract notice."]]
  },
  {
    i: 454,
    q: "As a highly ______ host, Arthur made sure that all of his guests had food, drinks, and someone friendly to talk to.",
    c: ["gregarious", "reclusive", "solitary", "reserved", "hostile"],
    a: "a",
    e: "Gregarious (adj.) means fond of company; sociable.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["gregarious", "Sociable; fond of company."]]
  },
  {
    i: 455,
    q: "The team’s ______ preparation for the launch ensured that not a single error occurred.",
    c: ["careless", "slapdash", "meticulous", "negligent", "lax"],
    a: "c",
    e: "Meticulous (adj.) means showing great attention to detail; very careful and precise.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["meticulous", "Very careful and precise attention to detail."]]
  },
  {
    i: 456,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 457,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 458,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 19,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 459,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 460,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 461,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 462,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 19,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 463,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 19,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 464,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 465,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 466,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 467,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 19,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 468,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 469,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 470,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 471,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 472,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 473,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 19,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 474,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 19,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 475,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 19,
    v: [["divergent", "Developing in different directions."]]
  },

  // CHAPTER 20 (476 - 500 - Note Q501 will be 476 to 501 in Chapter 20)
  {
    i: 476,
    q: "The ______ tropical weather began with bright morning sun but turned into an intense storm by noon.",
    c: ["stable", "predictable", "constant", "capricious", "static"],
    a: "d",
    e: "Capricious (adj.) means given to sudden and unaccountable changes of mood or behavior.",
    d: "intermediate",
    t: "cause_effect",
    ch: 20,
    v: [["capricious", "Given to sudden, unpredictable changes."]]
  },
  {
    i: 477,
    q: "The director hired Helen because she was a highly ______ actor, capable of playing both comedy and tragedy.",
    c: ["rigid", "versatile", "stubborn", "monotonous", "unyielding"],
    a: "b",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["versatile", "Able to adapt to many styles/roles."]]
  },
  {
    i: 478,
    q: "Because the pond contains ______ water and does not move, it serves as a breeding ground for mosquitoes.",
    c: ["flowing", "rapid", "stagnant", "vibrant", "turbulent"],
    a: "c",
    e: "Stagnant (adj.) of a body of water or the atmosphere, having no current or flow and often having an unpleasant smell as a consequence.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["stagnant", "Not flowing or moving; inactive."]]
  },
  {
    i: 479,
    q: "Her semester studying abroad had a ______ impact on her worldview, changing her career plans completely.",
    c: ["profound", "trivial", "minor", "insignificant", "superficial"],
    a: "a",
    e: "Profound (adj.) of a state, quality, or emotion, very great or intense.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["profound", "Very great or intense; deep."]]
  },
  {
    i: 480,
    q: "The artist’s beautiful sand sculpture was a(n) ______ creation that washed away on the evening tide.",
    c: ["imperishable", "permanent", "transient", "chronic", "enduring"],
    a: "c",
    e: "Transient (adj.) means lasting only for a short time; impermanent.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["transient", "Lasting only for a short time; impermanent."]]
  },
  {
    i: 481,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 482,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 483,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 20,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 484,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 485,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 486,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 487,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 20,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 488,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 20,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 489,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 490,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 491,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 492,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 20,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 493,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 494,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 495,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 496,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 497,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 498,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 20,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 499,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 500,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 20,
    v: [["divergent", "Developing in different directions."]]
  },
  {
    i: 501,
    q: "The student’s ______ study habits resulted in outstanding academic excellence across all subjects.",
    c: ["negligent", "indolent", "diligent", "lax", "slapdash"],
    a: "c",
    e: "Diligent (adj.) means showing care and conscientiousness in one's work or duties. This matches the context of outstanding academic excellence.",
    d: "easy",
    t: "cause_effect",
    ch: 20,
    v: [["diligent", "Having or showing care and conscientiousness in one's work."]]
  }
];
