import { CompactQuestion } from './sc_chunk_1';

export const chunk4: CompactQuestion[] = [
  // CHAPTER 13 (301 - 325)
  {
    i: 301,
    q: "Deciding that the child’s persistent temper tantrums were a behavioral ______ , the pediatrician sent him to a specialist.",
    c: ["stigma", "maxim", "hierarchy", "anomaly", "pinnacle"],
    a: "d",
    e: "An anomaly (n.) is something that deviates from what is standard, normal, or expected.",
    d: "advanced",
    t: "restatement",
    ch: 13,
    v: [["anomaly", "Deviates from standard or normal."]]
  },
  {
    i: 302,
    q: "With a wink and a nod, the supervisors gave their ______ approval to the plan.",
    c: ["clear", "explicit", "vociferous", "tacit", "superficial"],
    a: "d",
    e: "Tacit (adj.) means understood or implied without being directly stated in words.",
    d: "intermediate",
    t: "cause_effect",
    ch: 13,
    v: [["tacit", "Implied/understood without words."]]
  },
  {
    i: 303,
    q: "The constant ringing of cell phones is a modern ______ that many people find highly irritating.",
    c: ["boon", "intrusion", "blessing", "utility", "maxim"],
    a: "b",
    e: "An intrusion (n.) is the act of putting oneself or something deliberately into a place where it is unwelcome/uninvited.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["intrusion", "Unwelcome entry or disruption."]]
  },
  {
    i: 304,
    q: "The speaker's ______ and repetitive presentation tried our patience during the afternoon seminar.",
    c: ["lucid", "concise", "verbose", "articulate", "disinterred"],
    a: "c",
    e: "Verbose (adj.) means using or expressed in more words than are needed.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["verbose", "Wordy; using too many words."]]
  },
  {
    i: 305,
    q: "Having lived in the suburbs all her life, she felt completely like a ______ in the bustling metropolises.",
    c: ["pariah", "zealot", "denizen", "compatriot", "mentor"],
    a: "a",
    e: "A pariah (n.) is an outcast or someone shunned by a community.",
    d: "advanced",
    t: "contrast",
    ch: 13,
    v: [["pariah", "An outcast; shunned individual."]]
  },
  {
    i: 306,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 307,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 308,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 13,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 309,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 110,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 311,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 312,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 13,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 313,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 13,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 314,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 315,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 316,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 317,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 13,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 318,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 319,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 320,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 321,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 322,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 323,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 13,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 324,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 13,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 325,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 13,
    v: [["divergent", "Developing in different directions."]]
  },

  // CHAPTER 14 (326 - 350)
  {
    i: 326,
    q: "The chef’s ______ creations are loved by food critics all over the city.",
    c: ["insipid", "savory", "unpalatable", "bland", "fetid"],
    a: "b",
    e: "Savory (adj.) means belonging to the category of salty or spicy rather than sweet; appetizing.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["savory", "Appetizing; spicy or salty taste."]]
  },
  {
    i: 327,
    q: "The failing retail company had to ______ its remaining inventory to pay off debts.",
    c: ["accumulate", "hoard", "liquidate", "renovate", "saturate"],
    a: "c",
    e: "To liquidate (v.) means to convert assets into cash or wind up the affairs of a business.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["liquidate", "Wind up affairs; sell off assets."]]
  },
  {
    i: 328,
    q: "Her brother’s ______ rules made it impossible to predict what would upset him next.",
    c: ["equable", "systematic", "arbitrary", "consistent", "standard"],
    a: "c",
    e: "Arbitrary (adj.) means based on random choice or personal whim, rather than any system.",
    d: "easy",
    t: "restatement",
    ch: 14,
    v: [["arbitrary", "Based on random whim; unsystematic."]]
  },
  {
    i: 329,
    q: "The general issued a ______ strike to neutralize the enemy’s threat before they could attack.",
    c: ["delayed", "preemptive", "afterthought", "remedial", "reactive"],
    a: "b",
    e: "Preemptive (adj.) means serving or intended to forestall or prevent an attack or action.",
    d: "intermediate",
    t: "cause_effect",
    ch: 14,
    v: [["preemptive", "Forestalling or preventing an action."]]
  },
  {
    i: 330,
    q: "The experienced high school teacher was admired for her ______ temperament; she never grew angry.",
    c: ["volatile", "capricious", "equable", "choleric", "irascible"],
    a: "c",
    e: "Equable (adj.) means not easily disturbed or angered; calm and even-tempered.",
    d: "intermediate",
    t: "contrast",
    ch: 14,
    v: [["equable", "Calm, even-tempered, and stable."]]
  },
  {
    i: 331,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 332,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 333,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 14,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 334,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 335,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 336,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 337,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 14,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 338,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 14,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 339,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 340,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 341,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 342,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 14,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 343,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 344,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 345,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 346,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 347,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 348,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 14,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 349,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 14,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 350,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 14,
    v: [["divergent", "Developing in different directions."]]
  },

  // CHAPTER 15 (351 - 375)
  {
    i: 351,
    q: "The experienced mountain hikers had to ______ the narrow, steep ridge to reach the summit.",
    c: ["traverse", "abridge", "circumscribe", "confound", "subvert"],
    a: "a",
    e: "To traverse (v.) means to travel across or pass through.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["traverse", "Travel across or pass through."]]
  },
  {
    i: 352,
    q: "Due to a lack of immediate funding, the research project fell into a state of ______.",
    c: ["prosperity", "abeyance", "conformation", "activity", "escalation"],
    a: "b",
    e: "Abeyance (n.) is a state of temporary disuse, suspension, or inactivity.",
    d: "advanced",
    t: "cause_effect",
    ch: 15,
    v: [["abeyance", "State of temporary suspension or disuse."]]
  },
  {
    i: 353,
    q: "The child’s ______ reading skills amazed her elementary school teachers, as she was reading college materials.",
    c: ["tardy", "sluggish", "precocious", "stagnant", "remedial"],
    a: "c",
    e: "Precocious (adj.) means having developed certain abilities or proclivities at an earlier age than usual.",
    d: "advanced",
    t: "cause_effect",
    ch: 15,
    v: [["precocious", "Developing advanced skills at an early age."]]
  },
  {
    i: 354,
    q: "She gave a highly ______ and heartfelt eulogy that moved several audience members to tears.",
    c: ["insipid", "poignant", "indifferent", "apathetic", "detached"],
    a: "b",
    e: "Poignant (adj.) means evoking a keen sense of sadness, regret, or deep emotional performance.",
    d: "intermediate",
    t: "cause_effect",
    ch: 15,
    v: [["poignant", "Evoking a keen sense of sadness or emotion."]]
  },
  {
    i: 355,
    q: "The politician was heavily criticized for his public ______ and lack of concrete policy proposals.",
    c: ["brevity", "clarity", "bombast", "candor", "probity"],
    a: "c",
    e: "Bombast (n.) is high-sounding language with little meaning, used to impress people.",
    d: "advanced",
    t: "contrast",
    ch: 15,
    v: [["bombast", "High-sounding language lacking real meaning."]]
  },
  {
    i: 356,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 357,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 358,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 15,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 359,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 360,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 361,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 362,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 15,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 363,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 15,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 364,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 365,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 366,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 367,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 15,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 368,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 369,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 370,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 371,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 372,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 373,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 15,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 374,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 15,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 375,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 15,
    v: [["divergent", "Developing in different directions."]]
  },

  // CHAPTER 16 (376 - 400)
  {
    i: 376,
    q: "The continuous friction under intense heat caused the anchor rope to slowly ______.",
    c: ["fray", "condense", "solidify", "improve", "corroborate"],
    a: "a",
    e: "To fray (v.) is to unravel or become worn at the edge, especially through friction.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["fray", "Unravel or become worn, especially at the edges."]]
  },
  {
    i: 377,
    q: "The stressed receptionist’s ______ responses alienated several prospective clinic clients.",
    c: ["affable", "brusque", "verbose", "tactful", "deferential"],
    a: "b",
    e: "Brusque (adj.) means abrupt or offhand in speech or manner; curt.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["brusque", "Abrupt, curt, or offhand in speech or manner."]]
  },
  {
    i: 378,
    q: "The crisis manager remained completely ______ throughout the intense press briefing, calmly answering all loaded questions.",
    c: ["perturbed", "imperturbable", "volatile", "hysterical", "agitated"],
    a: "b",
    e: "Imperturbable (adj.) means unable to be upset or excited; calm and poised.",
    d: "advanced",
    t: "contrast",
    ch: 16,
    v: [["imperturbable", "Poised and calm; unable to be agitated."]]
  },
  {
    i: 379,
    q: "Her technical documentation was praised for being extremely ______ , explaining complex items in only several pages.",
    c: ["convoluted", "abstruse", "verbose", "concise", "redundant"],
    a: "d",
    e: "Concise (adj.) means giving a lot of information clearly and in a few words; brief and comprehensive.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["concise", "Brief and comprehensive; clear."]]
  },
  {
    i: 380,
    q: "He possessed a seemingly ______ appetite for historical non-fiction, checking out dozens of books every week.",
    c: ["insatiable", "sated", "scanty", "trivial", "apathetic"],
    a: "a",
    e: "Insatiable (adj.) means impossible to satisfy.",
    d: "intermediate",
    t: "cause_effect",
    ch: 16,
    v: [["insatiable", "Impossible to satisfy appetite."]]
  },
  {
    i: 381,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 382,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 383,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 16,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 384,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 385,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },
  {
    i: 386,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["erroneous", "Wrong; incorrect."]]
  },
  {
    i: 387,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 16,
    v: [["desiccate", "Dry out thoroughly; dehydrate."]]
  },
  {
    i: 388,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 16,
    v: [["modest", "Unassuming or moderate."]]
  },
  {
    i: 389,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 390,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 391,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 392,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 16,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 393,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 394,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 395,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 396,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 397,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 398,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 16,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 399,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 16,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 400,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 16,
    v: [["divergent", "Developing in different directions."]]
  }
];
