import { CompactQuestion } from './sc_chunk_1';

export const chunk3: CompactQuestion[] = [
  // CHAPTER 9 (201 - 225)
  {
    i: 201,
    q: "When Melinda arrived in the impoverished city, she was immediately ______ by bands of children begging for food.",
    c: ["bedraggled", "accosted", "infiltrated", "rebuked", "exacerbated"],
    a: "b",
    e: "To accost (v.) means to approach and address someone boldly or aggressively.",
    d: "advanced",
    t: "cause_effect",
    ch: 9,
    v: [["accosted", "Approached and addressed boldly/aggressively."]]
  },
  {
    i: 202,
    q: "According to the terms of the agreement, if Nicole defaulted on her loan, she would have to ______ her house and car.",
    c: ["usurp", "evince", "debut", "forfeit", "stigmatize"],
    a: "d",
    e: "To forfeit (v.) means to lose or be deprived of property or a right as a penalty for wrongdoing.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["forfeit", "Lose or be deprived of as a penalty."]]
  },
  {
    i: 203,
    q: "Tony was tired of his roommate’s petty ______ about his personal life, so he decided to move out.",
    c: ["appeasements", "quips", "quotas", "rallies", "iniquities"],
    a: "b",
    e: "A quip (n.) is a witty or sharp sarcastic remark.",
    d: "intermediate",
    t: "cause_effect",
    ch: 9,
    v: [["quips", "Witty, sarcastic, or sharp remarks."]]
  },
  {
    i: 204,
    q: "After fighting the five-alarm fire, the ______ firefighter could not relax enough to unwind and get some rest.",
    c: ["amicable", "treacherous", "pliable", "durable", "overwrought"],
    a: "e",
    e: "Overwrought (adj.) means in a state of nervous excitement or anxiety; extremely agitated.",
    d: "advanced",
    t: "cause_effect",
    ch: 9,
    v: [["overwrought", "In a state of nervous anxiety or extreme agitation."]]
  },
  {
    i: 205,
    q: "For years Henry bore the ______ of being the only man in five generations of his family not to make the varsity baseball team.",
    c: ["stigma", "brunt", "treatise", "scintillation", "punctiliousness"],
    a: "a",
    e: "A stigma (n.) is a mark of disgrace associated with a particular circumstance or quality.",
    d: "intermediate",
    t: "restatement",
    ch: 9,
    v: [["stigma", "A mark of disgrace associated with a circumstance."]]
  },
  {
    i: 206,
    q: "Traditionalists always criticize her ______ style of writing, preferring standard sentence structures.",
    c: ["decorous", "orthodox", "unconventional", "conforming", "equable"],
    a: "c",
    e: "Unconventional (adj.) means not based on or conforming to what is generally done or believed.",
    d: "easy",
    t: "contrast",
    ch: 9,
    v: [["unconventional", "Conforming to standard rules/beliefs."], ["orthodox", "Conforming to established rules."]]
  },
  {
    i: 207,
    q: "The rainforest's soil is ______ in rich nutrients, which supports a wide variety of diverse flora.",
    c: ["scanty", "arid", "abundant", "barren", "deficient"],
    a: "c",
    e: "Abundant (adj.) means existing or available in large quantities; overflowing.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["abundant", "Existing in large quantities."], ["deficient", "Inadequate in amount or quality."]]
  },
  {
    i: 208,
    q: "Rather than taking sides in the political debate, she remained completely ______ throughout.",
    c: ["partial", "prejudiced", "impartial", "passionate", "biased"],
    a: "c",
    e: "Impartial (adj.) means treating all rivals or disputants equally; fair and just.",
    d: "easy",
    t: "contrast",
    ch: 9,
    v: [["impartial", "Fair and just; unbiased."]]
  },
  {
    i: 209,
    q: "Because the ancient manuscript is legally ______ , the museum must keep it locked in a safe.",
    c: ["worthless", "counterfeit", "invaluable", "pliant", "sensitive"],
    a: "c",
    e: "Invaluable (adj.) means extremely useful; indispensable or highly valuable.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["invaluable", "Extremely useful; priceless."], ["counterfeit", "Made in exact imitation of something valuable."]]
  },
  {
    i: 210,
    q: "The speaker's delivery was so ______ that it put half the audience to sleep.",
    c: ["monotonous", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Monotonous (adj.) means dull, tedious, and repetitious; lacking in variety or interest.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["monotonous", "Lacking in variety or interest; dull."]]
  },
  {
    i: 211,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["intrinsic", "profound", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means appearing to be true or real only until examined more closely; shallow.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["superficial", "Shallowness of interest; superficial."], ["intrinsic", "Belonging naturally; essential."]]
  },
  {
    i: 212,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 213,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities.",
    d: "easy",
    t: "contrast",
    ch: 9,
    v: [["modest", "Unassuming; moderate."]]
  },
  {
    i: 214,
    q: "The company's primary strategy was to ______ its competitors by offering lower prices.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 215,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 216,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 217,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 9,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 218,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 219,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 220,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["debunk", "Expose the falseness of a myth."]]
  },
  {
    i: 221,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["superficial", "Occurring on the surface; shallow."]]
  },
  {
    i: 222,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["precise", "Exact and accurate."]]
  },
  {
    i: 223,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 9,
    v: [["catalyst", "A substance/event that speeds up change."]]
  },
  {
    i: 224,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 9,
    v: [["versatile", "Adaptable to many skills/styles."]]
  },
  {
    i: 225,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 9,
    v: [["divergent", "Developing in different directions."]]
  },

  // CHAPTER 10 (226 - 250)
  {
    i: 226,
    q: "When the house on the corner burned down, the entire neighborhood ______ together to help the victims re-establish their lives.",
    c: ["rallied", "recited", "skulked", "disintegrated", "expedited"],
    a: "a",
    e: "To rally (v.) means to come together for a common purpose or support.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["rally", "Bring or come together in order to support a cause."]]
  },
  {
    i: 227,
    q: "The massage therapist’s ______ fingers quickly eased the tension in Blanche’s back.",
    c: ["deft", "furtive", "listless", "tentative", "blithe"],
    a: "a",
    e: "Deft (adj.) means quick and skillful in physical movement; adroit.",
    d: "intermediate",
    t: "cause_effect",
    ch: 10,
    v: [["deft", "Skillful in physical movement."]]
  },
  {
    i: 228,
    q: "Jade’s parents were in ______ about the decision not to allow her to drive the family car to the prom; they both agreed that it would be unsafe.",
    c: ["affluence", "redress", "refraction", "discord", "unison"],
    a: "e",
    e: "Unison (n.) means perfect agreement or accord; acting as one.",
    d: "intermediate",
    t: "cause_effect",
    ch: 10,
    v: [["unison", "Perfect agreement or joint action."]]
  },
  {
    i: 229,
    q: "As she walked through the halls of her old grade school, Madeline became ______ , remembering her old friends and teachers.",
    c: ["prolific", "nostalgic", "credulous", "precocious", "ambitious"],
    a: "b",
    e: "Nostalgic (adj.) means sentimentally yearning for a point or memory in the past.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["nostalgic", "Exhibiting sentimental longing for the past."]]
  },
  {
    i: 230,
    q: "After being cleared of all charges for slander, the attorney was able to go back to work and ______ his role as a prosecutor.",
    c: ["inhibit", "reprimand", "remand", "resume", "dissipate"],
    a: "d",
    e: "To resume (v.) means to take up again after interruption.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["resume", "Begin to do or pursue something again."]]
  },
  {
    i: 231,
    q: "The continuous dry heat caused the lake to ______ and dry out completely.",
    c: ["expand", "overflow", "evaporate", "saturate", "congeal"],
    a: "c",
    e: "Evaporate (v.) means to turn from liquid into vapor.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["evaporate", "Turn into vapor; dry up."]]
  },
  {
    i: 232,
    q: "Scientific testing served to ______ the researcher's radical theory about cell division.",
    c: ["debunk", "invalidate", "validate", "subvert", "contradict"],
    a: "c",
    e: "Validate (v.) means to check or prove the validity or accuracy of.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["validate", "Prove to be accurate and true."]]
  },
  {
    i: 233,
    q: "The historic manuscript is so ______ that it must be stored in a climate-controlled vault.",
    c: ["robust", "durable", "fragile", "pliant", "elastic"],
    a: "c",
    e: "Fragile (adj.) means easily damaged, broken, or delicate.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["fragile", "Delicate; easily damaged."]]
  },
  {
    i: 234,
    q: "Unlike his brother who enjoys social gatherings, Julian is completely ______.",
    c: ["gregarious", "extroverted", "reclusive", "convivial", "hospitable"],
    a: "c",
    e: "Reclusive (adj.) means avoiding the company of other people; solitary.",
    d: "easy",
    t: "contrast",
    ch: 10,
    v: [["reclusive", "Solitary; avoiding others."]]
  },
  {
    i: 235,
    q: "The manager's ______ remarks directly insulted several of the hard-working employees.",
    c: ["laudatory", "deferential", "disparaging", "objective", "equitable"],
    a: "c",
    e: "Disparaging (adj.) means expressing the opinion that something or someone is of little worth; derogatory.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["disparaging", "Derogatory; belittling."]]
  },
  {
    i: 236,
    q: "The software update is ______ ; all system users must complete the download to ensure safety.",
    c: ["optional", "compulsory", "ancillary", "discretionary", "superfluous"],
    a: "b",
    e: "Compulsory (adj.) means required by law or a rule; obligatory or mandatory.",
    d: "easy",
    t: "restatement",
    ch: 10,
    v: [["compulsory", "Obligatory; mandatory."]]
  },
  {
    i: 237,
    q: "The ancient text was so ______ that only specialized classical scholars could understand its meaning.",
    c: ["lucid", "transparent", "obscure", "explicit", "coherent"],
    a: "c",
    e: "Obscure (adj.) means not discovered or known about; uncertain or difficult to understand.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["obscure", "Difficult to understand."]]
  },
  {
    i: 238,
    q: "Rather than providing a useful solution, the manager gave an empty ______ about hard work.",
    c: ["wisdom", "insight", "platitude", "revelation", "epiphany"],
    a: "c",
    e: "A platitude (n.) is a remark or statement, especially one with a moral content, that has been used too often to be interesting or thoughtful.",
    d: "intermediate",
    t: "restatement",
    ch: 10,
    v: [["platitude", "A cliché; overused moral statement."]]
  },
  {
    i: 239,
    q: "Because the local economy was so ______ , many families moved to neighboring cities in search of work.",
    c: ["vibrant", "robust", "stagnant", "prosperous", "flourishing"],
    a: "c",
    e: "Stagnant (adj.) means having no activity, progress, or growth; inactive.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["stagnant", "Inactive; lacking development."]]
  },
  {
    i: 240,
    q: "The continuous dry heat caused the flowers to ______ and droop toward the soil.",
    c: ["flourish", "wilt", "germinate", "bloom", "blossom"],
    a: "b",
    e: "Wilt (v.) means to become limp through heat, loss of water, or disease; droop.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["wilt", "Droop and dry out."]]
  },
  {
    i: 241,
    q: "To prove the validity of her scientific claim, the researcher must ______ her theory with concrete experimental data.",
    c: ["debunk", "invalidate", "corroborate", "subvert", "repudiate"],
    a: "c",
    e: "Corroborate (v.) means to confirm or give support to (a statement, theory, or finding).",
    d: "intermediate",
    t: "cause_effect",
    ch: 10,
    v: [["corroborate", "Confirm or support with evidence."]]
  },
  {
    i: 242,
    q: "The company's primary policy was to ______ its client list by building strong customer relationships.",
    c: ["dwindle", "expand", "curtail", "liquidate", "subvert"],
    a: "b",
    e: "Expand (v.) means to become or make larger or more extensive.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["expand", "Make larger or more extensive."]]
  },
  {
    i: 243,
    q: "His argument was entirely ______ , containing multiple logical fallacies and clear errors.",
    c: ["factual", "specious", "impeccable", "valid", "sound"],
    a: "b",
    e: "Specious (adj.) means superficially plausible, but actually wrong.",
    d: "intermediate",
    t: "restatement",
    ch: 10,
    v: [["specious", "Superficially true but actually false."]]
  },
  {
    i: 244,
    q: "The unexpected travel delay was merely a ______ inconvenience that did not disrupt their entire vacation plans.",
    c: ["chronic", "perpetual", "trivial", "catastrophic", "monumental"],
    a: "c",
    e: "Trivial (adj.) means of little value or importance.",
    d: "easy",
    t: "contrast",
    ch: 10,
    v: [["trivial", "Of little importance; minor."]]
  },
  {
    i: 245,
    q: "The newly hired apprentice was so ______ that she learned the complex manufacturing process in single week.",
    c: ["obtuse", "sluggish", "apt", "indolent", "hostile"],
    a: "c",
    e: "Apt (adj.) means quick to learn; intelligent or suited.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["apt", "Quick to learn; intelligent."]]
  },
  {
    i: 246,
    q: "The judge was widely praised for her ______ decisions, which were always completely free of personal bias.",
    c: ["arbitrary", "subjective", "equitable", "partial", "biased"],
    a: "c",
    e: "Equitable (adj.) means fair and impartial.",
    d: "intermediate",
    t: "cause_effect",
    ch: 10,
    v: [["equitable", "Fair and impartial."]]
  },
  {
    i: 247,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the major labor dispute.",
    c: ["biased", "partial", "disinterested", "passionate", "prejudiced"],
    a: "c",
    e: "Disinterested (adj.) means not influenced by considerations of personal advantage; impartial/unbiased.",
    d: "intermediate",
    t: "contrast",
    ch: 10,
    v: [["disinterested", "Impartial; objective."]]
  },
  {
    i: 248,
    q: "The continuous dry heat caused the flowers to ______ and droop toward the dirt.",
    c: ["blossom", "flourish", "wilt", "bloom", "germinate"],
    a: "c",
    e: "Wilt (v.) means to become limp through heat or lack of water; droop.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["wilt", "Droop and dry out."]]
  },
  {
    i: 249,
    q: "He spent years in a state of complete ______ after his farm was ruined by the severe plague.",
    c: ["affluence", "vitality", "lethargy", "prosperity", "affability"],
    a: "c",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 10,
    v: [["lethargy", "Lack of energy/sluggishness."]]
  },
  {
    i: 250,
    q: "Unlike her sister who makes decisions quickly, Jane is incredibly ______.",
    c: ["decisive", "resolute", "indecisive", "rash", "impetuous"],
    a: "c",
    e: "Indecisive (adj.) means not providing a clear and definite result; hesitating.",
    d: "easy",
    t: "contrast",
    ch: 10,
    v: [["indecisive", "Unable to make choices quickly."]]
  },

  // CHAPTER 11 (251 - 275)
  {
    i: 251,
    q: "The queen’s ______ fell ill during his journey and was unable to negotiate on her behalf when he arrived.",
    c: ["penury", "miscreant", "emissary", "denizen", "zealot"],
    a: "c",
    e: "An emissary (n.) is an agent sent on a mission to represent the interests of another.",
    d: "advanced",
    t: "restatement",
    ch: 11,
    v: [["emissary", "A person sent on a diplomatic mission."]]
  },
  {
    i: 252,
    q: "Tai was ______ by a series of setbacks that nearly made him miss his deadline.",
    c: ["ensconced", "relegated", "beleaguered", "solicited", "winnowed"],
    a: "c",
    e: "To beleaguer (v.) means to harass, beset, block, or besiege with difficulties.",
    d: "advanced",
    t: "cause_effect",
    ch: 11,
    v: [["beleaguered", "Beset with difficulties; harassed."]]
  },
  {
    i: 253,
    q: "New York boasts many ______ restaurants—places that are elegant and frequented by famous movie stars.",
    c: ["pungent", "posh", "diminutive", "mediocre", "middling"],
    a: "b",
    e: "Posh (adj.) means elegant, luxurious, and highly fashionable.",
    d: "easy",
    t: "restatement",
    ch: 11,
    v: [["posh", "Elegant, fashionable, and luxurious."]]
  },
  {
    i: 254,
    q: "Although she appeared confident, once she began her speech, the valedictorian’s ______ voice indicated her nervousness.",
    c: ["supercilious", "resonant", "tenuous", "placating", "tremulous"],
    a: "e",
    e: "Tremulous (adj.) means characterized by quivering, trembling, or instability due to fear or nervousness.",
    d: "intermediate",
    t: "contrast",
    ch: 11,
    v: [["tremulous", "Shaking or quivering slightly; nervous."]]
  },
  {
    i: 255,
    q: "A charming painting of a pleasant ______ landscape hung above Vitaly’s fireplace, in marked contrast to the noise of the bustling city.",
    c: ["nascent", "histrionic", "bucolic", "indigenous", "ersatz"],
    a: "c",
    e: "Bucolic (adj.) means of or characteristic of pleasant country life, rural, or pastoral scenery.",
    d: "advanced",
    t: "contrast",
    ch: 11,
    v: [["bucolic", "Pleasant country-like or rural life."]]
  },
  {
    i: 256,
    q: "In contrast to Marcus's generally morose behavior, Julian is always extremely ______.",
    c: ["sullen", "ebullient", "glum", "gloom", "reserved"],
    a: "b",
    e: "Ebullient (adj.) means cheerful and full of energy; exuberant.",
    d: "easy",
    t: "contrast",
    ch: 11,
    v: [["ebullient", "Exuberantly cheerful/energetic."]]
  },
  {
    i: 257,
    q: "Because her accounts were known for perfect ______ , no one doubted Jane’s testimony.",
    c: ["guile", "mendacity", "veracity", "cupidity", "artifice"],
    a: "c",
    e: "Veracity (n.) is conformity to facts; accuracy or truthfulness.",
    d: "intermediate",
    t: "cause_effect",
    ch: 11,
    v: [["veracity", "Truthfulness; accuracy."]]
  },
  {
    i: 258,
    q: "The mountain trail was structurally ______ due to the recent rainstorm and mud slides.",
    c: ["sound", "durable", "precarious", "robust", "safe"],
    a: "c",
    e: "Precarious (adj.) means not securely held; dangerously unstable or unsafe.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["precarious", "Dangerously unstable; unsafe."]]
  },
  {
    i: 259,
    q: "Rather than giving a direct answer, the witness gave an ______ response that frustrated the judge.",
    c: ["lucid", "evasive", "explicit", "candid", "transparent"],
    a: "b",
    e: "Evasive (adj.) means tending to avoid commitment or response, especially by responding indirectly.",
    d: "easy",
    t: "contrast",
    ch: 11,
    v: [["evasive", "Avoiding direct commitment."]]
  },
  {
    i: 260,
    q: "The business failed due to the directors’ public reputation for ______ and greed.",
    c: ["probity", "frugality", "avarice", "generosity", "benevolence"],
    a: "c",
    e: "Avarice (n.) is extreme greed for wealth or material gain.",
    d: "intermediate",
    t: "cause_effect",
    ch: 11,
    v: [["avarice", "Extreme greed for wealth."]]
  },
  {
    i: 261,
    q: "The judge was praised for her ______ decisions, which were always completely free of bias.",
    c: ["biased", "partial", "equitable", "arbitrary", "subjective"],
    a: "c",
    e: "Equitable (adj.) means fair and impartial.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["equitable", "Fair and impartial."]]
  },
  {
    i: 262,
    q: "The computer interface was designed to be ______ so that users could navigate it without training.",
    c: ["intuitive", "convoluted", "abstruse", "obscure", "rigid"],
    a: "a",
    e: "Intuitive (adj.) means easy to use and understand without explicit instruction.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["intuitive", "Easy to understand immediately."]]
  },
  {
    i: 263,
    q: "His speeches were filled with meaningless ______ that added little of substance to the debate.",
    c: [" sabiduría", "rhetoric", "coherence", "conciseness", "brevity"],
    a: "b",
    e: "Rhetoric (n.) is language designed to have a persuasive effect, but which is often seen as lacking substance.",
    d: "easy",
    t: "restatement",
    ch: 11,
    v: [["rhetoric", "Persuasive language lacking substance."]]
  },
  {
    i: 264,
    q: "The dry wind caused the lake level to ______ significantly during the summer.",
    c: ["overflow", "expand", "subside", "saturate", "oscillate"],
    a: "c",
    e: "Subside (v.) means to sink or settle down to a lower or less active level.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["subside", "Go down to a lower level; sink."]]
  },
  {
    i: 265,
    q: "The young student was so ______ that she learned the classical language in single semester.",
    c: ["obtuse", "indolent", "apt", "negligent", "sluggish"],
    a: "c",
    e: "Apt (adj.) means quick to learn; suited or intelligent.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["apt", "Quick to learn; suited."]]
  },
  {
    i: 266,
    q: "The queen’s ______ fell ill during his journey and was unable to negotiate on her behalf when he arrived.",
    c: ["penury", "miscreant", "emissary", "denizen", "zealot"],
    a: "c",
    e: "An emissary (n.) is an agent sent on a mission to represent the interests of another.",
    d: "advanced",
    t: "restatement",
    ch: 11,
    v: [["emissary", "A person sent on a diplomatic mission."]]
  },
  {
    i: 267,
    q: "Tai was ______ by a series of setbacks that nearly made him miss his deadline.",
    c: ["ensconced", "relegated", "beleaguered", "solicited", "winnowed"],
    a: "c",
    e: "To beleaguer (v.) means to harass, beset, block, or besiege with difficulties.",
    d: "advanced",
    t: "cause_effect",
    ch: 11,
    v: [["beleaguered", "Beset with difficulties; harassed."]]
  },
  {
    i: 268,
    q: "New York boasts many ______ restaurants—places that are elegant and frequented by famous movie stars.",
    c: ["pungent", "posh", "diminutive", "mediocre", "middling"],
    a: "b",
    e: "Posh (adj.) means elegant, luxurious, and highly fashionable.",
    d: "easy",
    t: "restatement",
    ch: 11,
    v: [["posh", "Elegant, fashionable, and luxurious."]]
  },
  {
    i: 269,
    q: "Although she appeared confident, once she began her speech, the valedictorian’s ______ voice indicated her nervousness.",
    c: ["supercilious", "resonant", "tenuous", "placating", "tremulous"],
    a: "e",
    e: "Tremulous (adj.) means characterized by quivering, trembling, or instability due to fear or nervousness.",
    d: "intermediate",
    t: "contrast",
    ch: 11,
    v: [["tremulous", "Shaking or quivering slightly; nervous."]]
  },
  {
    i: 270,
    q: "A charming painting of a pleasant ______ landscape hung above Vitaly’s fireplace, in marked contrast to the noise of the bustling city.",
    c: ["nascent", "histrionic", "bucolic", "indigenous", "ersatz"],
    a: "c",
    e: "Bucolic (adj.) means of or characteristic of pleasant country life, rural, or pastoral scenery.",
    d: "advanced",
    t: "contrast",
    ch: 11,
    v: [["bucolic", "Pleasant country-like or rural life."]]
  },
  {
    i: 271,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 272,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["arid", "Extremely dry; barren."]]
  },
  {
    i: 273,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 11,
    v: [["objective", "Impartial; fair."]]
  },
  {
    i: 274,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["immune", "Resistant; highly protected."]]
  },
  {
    i: 275,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 11,
    v: [["insipid", "Lacking vigor or interest; dull."]]
  },

  // CHAPTER 12 (276 - 300)
  {
    i: 276,
    q: "Claude felt particularly ______ as he carried the large satchel filled with cash through the dark streets.",
    c: ["inclusive", "vulnerable", "reclusive", "unwieldy", "torrential"],
    a: "b",
    e: "Vulnerable (adj.) means open to physical or emotional attack or harm.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["vulnerable", "Susceptible to attack or harm."]]
  },
  {
    i: 277,
    q: "Niall’s ______ attitude toward the boss is embarrassing; he does nearly everything for him!",
    c: ["subservient", "subversive", "subtle", "sundry", "surly"],
    a: "a",
    e: "Subservient (adj.) means excessively submissive or acting in a servantlike, obedient manner.",
    d: "intermediate",
    t: "restatement",
    ch: 12,
    v: [["subservient", "Excessively submissive/servantlike."]]
  },
  {
    i: 278,
    q: "Although she was a successful professional, Debra’s inability to accurately complete her taxes made her feel a bit ______.",
    c: ["endow", "rapturous", "ravenous", "obtuse", "elated"],
    a: "d",
    e: "Obtuse (adj.) means annoyingly insensitive or slow to understand.",
    d: "advanced",
    t: "contrast",
    ch: 12,
    v: [["obtuse", "Slow to understand/perceive."]]
  },
  {
    i: 279,
    q: "Although it was supposed to be written for the general public, the report was so ______ that only those with inside knowledge could understand it.",
    c: ["indigenous", "ebullient", "truculent", "pugnacious", "esoteric"],
    a: "e",
    e: "Esoteric (adj.) means intended for or likely to be understood by only a small number of people with specialized knowledge.",
    d: "advanced",
    t: "contrast",
    ch: 12,
    v: [["esoteric", "Understood by only an inner circle."]]
  },
  {
    i: 280,
    q: "Francois fell into a groggy ______ after having suffered a high fever for several days.",
    c: ["profundity", "sluggard", "verve", "stupor", "grovel"],
    a: "d",
    e: "A stupor (n.) is a state of near-unconsciousness or profound lethargy.",
    d: "advanced",
    t: "cause_effect",
    ch: 12,
    v: [["stupor", "A state of near-unconsciousness or insensibility."]]
  },
  {
    i: 281,
    q: "When Melinda arrived in the impoverished city, she was immediately ______ by bands of children begging for food.",
    c: ["bedraggled", "accosted", "infiltrated", "rebuked", "exacerbated"],
    a: "b",
    e: "To accost (v.) means to approach and address someone boldly or aggressively.",
    d: "advanced",
    t: "cause_effect",
    ch: 12,
    v: [["accosted", "Approached and addressed boldly/aggressively."]]
  },
  {
    i: 282,
    q: "According to the terms of the agreement, if Nicole defaulted on her loan, she would have to ______ her house and car.",
    c: ["usurp", "evince", "debut", "forfeit", "stigmatize"],
    a: "d",
    e: "To forfeit (v.) means to lose or be deprived of property or a right as a penalty for wrongdoing.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["forfeit", "Lose or be deprived of as a penalty."]]
  },
  {
    i: 283,
    q: "Tony was tired of his roommate’s petty ______ about his personal life, so he decided to move out.",
    c: ["appeasements", "quips", "quotas", "rallies", "iniquities"],
    a: "b",
    e: "A quip (n.) is a witty or sharp sarcastic remark.",
    d: "intermediate",
    t: "cause_effect",
    ch: 12,
    v: [["quips", "Witty, sarcastic, or sharp remarks."]]
  },
  {
    i: 284,
    q: "After fighting the five-alarm fire, the ______ firefighter could not relax enough to unwind and get some rest.",
    c: ["amicable", "treacherous", "pliable", "durable", "overwrought"],
    a: "e",
    e: "Overwrought (adj.) means in a state of nervous excitement or anxiety; extremely agitated.",
    d: "advanced",
    t: "cause_effect",
    ch: 12,
    v: [["overwrought", "In a state of nervous anxiety or extreme agitation."]]
  },
  {
    i: 285,
    q: "For years Henry bore the ______ of being the only man in five generations of his family not to make the varsity baseball team.",
    c: ["stigma", "brunt", "treatise", "scintillation", "punctiliousness"],
    a: "a",
    e: "A stigma (n.) is a mark of disgrace associated with a particular circumstance or quality.",
    d: "intermediate",
    t: "restatement",
    ch: 12,
    v: [["stigma", "A mark of disgrace associated with a circumstance."]]
  },
  {
    i: 286,
    q: "Traditionalists always criticize her ______ style of writing, preferring standard sentence structures.",
    c: ["decorous", "orthodox", "unconventional", "conforming", "equable"],
    a: "c",
    e: "Unconventional (adj.) means not based on or conforming to what is generally done or believed.",
    d: "easy",
    t: "contrast",
    ch: 12,
    v: [["unconventional", "Conforming to standard rules/beliefs."]]
  },
  {
    i: 287,
    q: "The rainforest's soil is ______ in rich nutrients, which supports a wide variety of diverse flora.",
    c: ["scanty", "arid", "abundant", "barren", "deficient"],
    a: "c",
    e: "Abundant (adj.) means existing or available in large quantities; overflowing.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["abundant", "Existing in large quantities."]]
  },
  {
    i: 288,
    q: "Rather than taking sides in the political debate, she remained completely ______ throughout.",
    c: ["partial", "prejudiced", "impartial", "passionate", "biased"],
    a: "c",
    e: "Impartial (adj.) means treating all rivals or disputants equally; fair and just.",
    d: "easy",
    t: "contrast",
    ch: 12,
    v: [["impartial", "Fair and just; unbiased."]]
  },
  {
    i: 289,
    q: "Because the ancient manuscript is legally ______ , the museum must keep it locked in a safe.",
    c: ["worthless", "counterfeit", "invaluable", "pliant", "sensitive"],
    a: "c",
    e: "Invaluable (adj.) means extremely useful; indispensable or highly valuable.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["invaluable", "Extremely useful; priceless."]]
  },
  {
    i: 290,
    q: "The speaker's delivery was so ______ that it put half the audience to sleep.",
    c: ["monotonous", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Monotonous (adj.) means dull, tedious, and repetitious; lacking in variety or interest.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["monotonous", "Lacking in variety or interest; dull."]]
  },
  {
    i: 291,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["intrinsic", "profound", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means appearing to be true or real only until examined more closely; shallow.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["superficial", "Shallowness of interest; superficial."]]
  },
  {
    i: 292,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["eccentric", "Unconventional and strange."]]
  },
  {
    i: 293,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities.",
    d: "easy",
    t: "contrast",
    ch: 12,
    v: [["modest", "Unassuming; moderate."]]
  },
  {
    i: 294,
    q: "The company's primary strategy was to ______ its competitors by offering lower prices.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["undercut", "Offer services at a lower price than."]]
  },
  {
    i: 295,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["genial", "Friendly and cheerful."]]
  },
  {
    i: 296,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["lethargy", "A lack of energy and enthusiasm."]]
  },
  {
    i: 297,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 12,
    v: [["vacillating", "Indecisive; wavering."]]
  },
  {
    i: 298,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["ambiguous", "Open to multiple interpretations."]]
  },
  {
    i: 299,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["precarious", "Unstable and dangerous."]]
  },
  {
    i: 300,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 12,
    v: [["debunk", "Expose the falseness of a myth."]]
  }
];
