import { CompactQuestion } from './sc_chunk_1';

export const chunk2: CompactQuestion[] = [
  // CHAPTER 5 (101 - 125)
  {
    i: 101,
    q: "Amie agrees with the ______ that the grass is always greener on the other side of the fence.",
    c: ["perpetuity", "penchant", "maxim", "conformation", "fortitude"],
    a: "c",
    e: "A maxim (n.) is a short, concise statement expressing a general truth or rule of conduct.",
    d: "advanced",
    t: "restatement",
    ch: 5,
    v: [["maxim", "A statement expressing a general truth or rule of conduct."]]
  },
  {
    i: 102,
    q: "Victor Frankenstein’s creature was a(n) ______ , detested by everyone he met.",
    c: ["itinerant", "anathema", "cosmopolitan", "mercenary", "anomaly"],
    a: "b",
    e: "An anathema (n.) is something or someone that is vehemently disliked, detested, or shunned.",
    d: "advanced",
    t: "restatement",
    ch: 5,
    v: [["anathema", "Something or someone passionately detested or shunned."]]
  },
  {
    i: 103,
    q: "Jack Nicholson was at the ______ of his career when he received the Oscar for Best Actor.",
    c: ["detriment", "pinnacle", "oligarchy", "rogue", "repose"],
    a: "b",
    e: "A pinnacle (n.) is the highest, most successful point of a career or mountain.",
    d: "easy",
    t: "restatement",
    ch: 5,
    v: [["pinnacle", "The most successful point; peak."]]
  },
  {
    i: 104,
    q: "Ariana was outstanding as the moderator; she handled the heated debate with great ______ , keeping the conversation fair and on track.",
    c: ["finesse", "pretentiousness", "prowess", "succor", "aversion"],
    a: "a",
    e: "Finesse (n.) is the subtle, highly skillful, and diplomatic handling of a difficult situation.",
    d: "intermediate",
    t: "restatement",
    ch: 5,
    v: [["finesse", "Refinement or extreme delicacy in skill, performance, or diplomacy."]]
  },
  {
    i: 105,
    q: "The class endured a loud and lengthy ______ by the teacher on the subject of submitting homework on time.",
    c: ["guile", "polemic", "bravado", "tirade", "heresy"],
    a: "d",
    e: "A tirade (n.) is a long, angry speech of criticism or denunciation.",
    d: "intermediate",
    t: "restatement",
    ch: 5,
    v: [["tirade", "A long, angry speech of criticism or accusation."]]
  },
  {
    i: 106,
    q: "The candidate's ______ behavior lost him the support of his main conservative voters.",
    c: ["eccentric", "decorous", "prudent", "conforming", "equable"],
    a: "a",
    e: "Eccentric (adj.) means unconventional and slightly strange. It naturally alienates traditional voters.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["eccentric", "Unconventional and slightly strange."], ["decorous", "In keeping with good taste and propriety."]]
  },
  {
    i: 107,
    q: "The desert climate is extremely ______ , with almost no vegetation capable of surviving the heat.",
    c: ["arid", "humid", "luxuriant", "temperate", "saturated"],
    a: "a",
    e: "Arid (adj.) means having little or no rain; too dry or barren to support vegetation.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["arid", "Extremely dry; barren."], ["luxuriant", "Abundant and rich in growth."]]
  },
  {
    i: 108,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the negotiation.",
    c: ["partial", "prejudiced", "objective", "passionate", "biased"],
    a: "c",
    e: "Objective (adj.) means not influenced by personal feelings or opinions in considering and representing facts; impartial.",
    d: "easy",
    t: "contrast",
    ch: 5,
    v: [["objective", "Impartial; fair."], ["prejudiced", "Having a preconceived opinion not based on reason."]]
  },
  {
    i: 109,
    q: "The massive ancient structure was made of solid granite blocks, making it highly ______ to weathering.",
    c: ["susceptible", "immune", "vulnerable", "pliant", "sensitive"],
    a: "b",
    e: "Immune (adj.) means resistant to a particular or environmental effect.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["immune", "Resistant; highly protected."], ["susceptible", "Easily influenced or harmed."]]
  },
  {
    i: 110,
    q: "His speech was so ______ that it put half the audience to sleep.",
    c: ["insipid", "vibrant", "dynamic", "gripping", "provocative"],
    a: "a",
    e: "Insipid (adj.) means lacking vigor or interest; boring or bland.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["insipid", "Lacking vigor or interest; dull."], ["provocative", "Causing annoyance, anger, or interest."]]
  },
  {
    i: 111,
    q: "The primary flaw in his logic was a(n) ______ assumption that did not hold up under questioning.",
    c: ["sound", "empirical", "erroneous", "factual", "valid"],
    a: "c",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["erroneous", "Wrong; incorrect."], ["empirical", "Based on observation or experience."]]
  },
  {
    i: 112,
    q: "The continuous dry winds caused the soil to ______ and turn into fine dust.",
    c: ["congeal", "desiccate", "moisten", "irrigate", "solidify"],
    a: "b",
    e: "Desiccate (v.) means to dry thoroughly; remove the moisture from.",
    d: "advanced",
    t: "cause_effect",
    ch: 5,
    v: [["desiccate", "Dry out thoroughly; dehydrate."], ["congeal", "Solidify or coagulate."]]
  },
  {
    i: 113,
    q: "Despite her success, she remained extremely ______ about her academic achievements.",
    c: ["arrogant", "pretentious", "modest", "boastful", "haughty"],
    a: "c",
    e: "Modest (adj.) means unassuming or moderate in the estimation of one's abilities or achievements.",
    d: "easy",
    t: "contrast",
    ch: 5,
    v: [["modest", "Unassuming or moderate."], ["arrogant", "Having or revealing an exaggerated sense of one's own importance."]]
  },
  {
    i: 114,
    q: "The company's primary strategy was to ______ its competitors by lowering prices below market value.",
    c: ["underpin", "undercut", "corroborate", "substantiate", "foster"],
    a: "b",
    e: "Undercut (v.) means to offer goods or services at a lower price than a competitor.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["undercut", "Offer services at a lower price than."], ["corroborate", "Confirm or give support to."]]
  },
  {
    i: 115,
    q: "The manager's ______ and warm personality made him highly popular among the workers.",
    c: ["aloof", "belligerent", "genial", "surly", "haughty"],
    a: "c",
    e: "Genial (adj.) means friendly and cheerful.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["genial", "Friendly and cheerful."], ["surly", "Bad-tempered and unfriendly."]]
  },
  {
    i: 116,
    q: "He spent years in a state of complete ______ after his business collapsed and he lost his savings.",
    c: ["lethargy", "prosperity", "vitality", "jubilation", "affluence"],
    a: "a",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["lethargy", "A lack of energy and enthusiasm."], ["affluence", "The state of having a great deal of money; wealth."]]
  },
  {
    i: 117,
    q: "Unlike her sister who makes decisions quickly, Clara is incredibly ______.",
    c: ["resolute", "decisive", "vacillating", "rash", "impetuous"],
    a: "c",
    e: "Vacillating (adj.) means wavering between different opinions or actions; indecisive.",
    d: "intermediate",
    t: "contrast",
    ch: 5,
    v: [["vacillating", "Indecisive; wavering."], ["resolute", "Admirably purposeful, determined, and unwavering."]]
  },
  {
    i: 118,
    q: "The speaker's message was so ______ that it was impossible to discern her true intentions.",
    c: ["lucid", "explicit", "ambiguous", "straightforward", "transparent"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; having a double meaning.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["ambiguous", "Open to multiple interpretations."], ["explicit", "Stated clearly and in detail."]]
  },
  {
    i: 119,
    q: "Due to a lack of maintenance, the ancient bridge is now in a structurally ______ state.",
    c: ["sound", "durable", "precarious", "robust", "impenetrable"],
    a: "c",
    e: "Precarious (adj.) means not securely held or in position; dangerously unstable.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["precarious", "Unstable and dangerous."], ["robust", "Strong and healthy; vigorous."]]
  },
  {
    i: 120,
    q: "The researcher's primary goal was to ______ the myths surrounding the historical figure.",
    c: ["corroborate", "substantiate", "debunk", "validate", "propagate"],
    a: "c",
    e: "Debunk (v.) means to expose the falseness or hollowness of a myth, idea, or belief.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["debunk", "Expose the falseness of a myth."], ["propagate", "Spread and promote an idea widely."]]
  },
  {
    i: 121,
    q: "Her interest in classical philosophy was merely ______ ; she only studied it to impress her professors.",
    c: ["profound", "intrinsic", "superficial", "genuine", "absolute"],
    a: "c",
    e: "Superficial (adj.) means existing or occurring at or on the surface; not deep or spiritual.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["superficial", "Occurring on the surface; shallow."], ["intrinsic", "Belonging naturally; essential."]]
  },
  {
    i: 122,
    q: "The business partners developed a ______ agreement to avoid any future disputes over revenue.",
    c: ["vague", "verbal", "precise", "lax", "informal"],
    a: "c",
    e: "Precise (adj.) means marked by exactness and accuracy of expression or detail.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["precise", "Exact and accurate."], ["lax", "Not sufficiently strict, severe, or careful."]]
  },
  {
    i: 123,
    q: "The unexpected economic downturn served as a ______ for major business reforms.",
    c: ["hinderance", "barrier", "catalyst", "impediment", "obstacle"],
    a: "c",
    e: "A catalyst (n.) is a person or thing that precipitates an event or change.",
    d: "intermediate",
    t: "cause_effect",
    ch: 5,
    v: [["catalyst", "A substance/event that speeds up change."], ["impediment", "A hindrance or obstruction."]]
  },
  {
    i: 124,
    q: "The young artist was so ______ that she could adapt to any medium or style immediately.",
    c: ["rigid", "obstinate", "versatile", "inflexible", "monotonous"],
    a: "c",
    e: "Versatile (adj.) means able to adapt or be adapted to many different functions or activities.",
    d: "easy",
    t: "cause_effect",
    ch: 5,
    v: [["versatile", "Adaptable to many skills/styles."], ["obstinate", "Stubbornly refusing to change."]]
  },
  {
    i: 125,
    q: "Despite being twin brothers, their personalities are completely ______.",
    c: ["identical", "compatible", "divergent", "homogenous", "synonymous"],
    a: "c",
    e: "Divergent (adj.) means tending to be different or develop in different directions.",
    d: "easy",
    t: "contrast",
    ch: 5,
    v: [["divergent", "Developing in different directions."], ["homogeneous", "Of the same kind; alike."]]
  },

  // CHAPTER 6 (126 - 150)
  {
    i: 126,
    q: "People often referred to Noelle as ______ because she trusted everyone and slept with her doors unlocked.",
    c: ["naïve", "elevated", "boastful", "panoramic", "elated"],
    a: "a",
    e: "Naïve (adj.) means lacking worldly experience; possessing a childlike innocence or simplicity.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["naïve", "Showing a lack of experience, wisdom, or judgment."]]
  },
  {
    i: 127,
    q: "Kinnel’s re-election is being threatened by a growing ______ of disgruntled union members.",
    c: ["rogue", "faction", "pariah", "guise", "anathema"],
    a: "b",
    e: "A faction (n.) is a group or cleft within a larger group, usually representing opposing interests.",
    d: "intermediate",
    t: "restatement",
    ch: 6,
    v: [["faction", "A small organized dissenting group within a larger one."]]
  },
  {
    i: 128,
    q: "The peasants passed their weary days in much ______ and little comfort.",
    c: ["pertinence", "renown", "travail", "exile", "repose"],
    a: "c",
    e: "Travail (n.) means hard, painful, or painful physical labor.",
    d: "advanced",
    t: "contrast",
    ch: 6,
    v: [["travail", "Painful or laborious effort."]]
  },
  {
    i: 129,
    q: "Lyasia is a ______ of the clarinet; she has performed solos with orchestras all around the world.",
    c: ["neophyte", "novice", "virtuoso", "termagant", "plethora"],
    a: "c",
    e: "A virtuoso (n.) is a master of technique in classical arts or music.",
    d: "intermediate",
    t: "cause_effect",
    ch: 6,
    v: [["virtuoso", "A person highly skilled in music or artistic pursuits."]]
  },
  {
    i: 130,
    q: "The haunted house displayed ______ scenes in every room, causing squeamish visitors to scream.",
    c: ["preparatory", "archaic", "macabre", "precocious", "impetuous"],
    a: "c",
    e: "Macabre (adj.) means ghastly, horrible, or gruesome.",
    d: "intermediate",
    t: "cause_effect",
    ch: 6,
    v: [["macabre", "Disturbing and horrifying because of death themes."]]
  },
  {
    i: 131,
    q: "The speaker's ______ style of writing was praised for its balance and beauty.",
    c: ["clumsy", "verbose", "elegant", "garish", "cacophonous"],
    a: "c",
    e: "Elegant (adj.) means pleasingly graceful and stylish in appearance or manner.",
    d: "easy",
    t: "restatement",
    ch: 6,
    v: [["elegant", "Graceful and stylish."], ["cacophonous", "Involving a harsh, discordant mixture of sounds."]]
  },
  {
    i: 132,
    q: "The patient's health began to ______ rapidly after she stopped taking her prescribed medication.",
    c: ["ameliorate", "deteriorate", "stabilize", "renovate", "rally"],
    a: "b",
    e: "Deteriorate (v.) means to become progressively worse.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["deteriorate", "Become progressively worse."], ["ameliorate", "Make something bad better."]]
  },
  {
    i: 133,
    q: "The legal system is designed to be ______ , treating all citizens with equal fairness.",
    c: ["arbitrary", "impartial", "biased", "prejudiced", "subjective"],
    a: "b",
    e: "Impartial (adj.) means treating all rivals or disputants equally; fair and just.",
    d: "easy",
    t: "restatement",
    ch: 6,
    v: [["impartial", "Fair and just; unbiased."], ["arbitrary", "Based on random choice rather than reason."]]
  },
  {
    i: 134,
    q: "Her constant ______ made it extremely difficult for her to maintain any long-term friendships.",
    c: ["loyalty", "fickleness", "constancy", "fidelity", "probity"],
    a: "b",
    e: "Fickleness (n.) is changeability, especially in regards to affections, choices, or loyalties.",
    d: "intermediate",
    t: "cause_effect",
    ch: 6,
    v: [["fickleness", "Changeability in loyalty or choice."], ["probity", "The quality of strong morals."]]
  },
  {
    i: 135,
    q: "The continuous dry heat caused the lake to ______ and dry out completely.",
    c: ["expand", "overflow", "evaporate", "saturate", "congeal"],
    a: "c",
    e: "Evaporate (v.) means to turn from liquid into vapor.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["evaporate", "Turn into vapor; dry up."]]
  },
  {
    i: 136,
    q: "Scientific testing served to ______ the researcher's radical theory about cell division.",
    c: ["debunk", "invalidate", "validate", "subvert", "contradict"],
    a: "c",
    e: "Validate (v.) means to check or prove the validity or accuracy of.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["validate", "Prove to be accurate and true."], ["debunk", "Expose the falsehood of."]]
  },
  {
    i: 137,
    q: "The historic manuscript is so ______ that it must be stored in a climate-controlled vault.",
    c: ["robust", "durable", "fragile", "pliant", "elastic"],
    a: "c",
    e: "Fragile (adj.) means easily damaged, broken, or delicate.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["fragile", "Delicate; easily damaged."], ["robust", "Vigorous and strong."]]
  },
  {
    i: 138,
    q: "Unlike his brother who enjoys social gatherings, Julian is completely ______.",
    c: ["gregarious", "extroverted", "reclusive", "convivial", "hospitable"],
    a: "c",
    e: "Reclusive (adj.) means avoiding the company of other people; solitary.",
    d: "easy",
    t: "contrast",
    ch: 6,
    v: [["reclusive", "Solitary; avoiding others."], ["gregarious", "Convivial; fond of company."]]
  },
  {
    i: 139,
    q: "The manager's ______ remarks directly insulted several of the hard-working employees.",
    c: ["laudatory", "deferential", "disparaging", "objective", "equitable"],
    a: "c",
    e: "Disparaging (adj.) means expressing the opinion that something or someone is of little worth; derogatory.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["disparaging", "Derogatory; belittling."], ["laudatory", "Expressing praise or commendation."]]
  },
  {
    i: 140,
    q: "The software update is ______ ; all system users must complete the download to ensure safety.",
    c: ["optional", "compulsory", "ancillary", "discretionary", "superfluous"],
    a: "b",
    e: "Compulsory (adj.) means required by law or a rule; obligatory or mandatory.",
    d: "easy",
    t: "restatement",
    ch: 6,
    v: [["compulsory", "Obligatory; mandatory."], ["superfluous", "Unnecessary, especially through being more than enough."]]
  },
  {
    i: 141,
    q: "The ancient text was so ______ that only specialized classical scholars could understand its meaning.",
    c: ["lucid", "transparent", "obscure", "explicit", "coherent"],
    a: "c",
    e: "Obscure (adj.) means not discovered or known about; uncertain or difficult to understand.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["obscure", "Difficult to understand."], ["lucid", "Clear and easy to understand."]]
  },
  {
    i: 142,
    q: "Rather than providing a useful solution, the manager gave an empty ______ about hard work.",
    c: ["wisdom", "insight", "platitude", "revelation", "epiphany"],
    a: "c",
    e: "A platitude (n.) is a remark or statement, especially one with a moral content, that has been used too often to be interesting or thoughtful.",
    d: "intermediate",
    t: "restatement",
    ch: 6,
    v: [["platitude", "A cliché; overused moral statement."], ["revelation", "A surprising and previously unknown fact."]]
  },
  {
    i: 143,
    q: "Because the local economy was so ______ , many families moved to neighboring cities in search of work.",
    c: ["vibrant", "robust", "stagnant", "prosperous", "flourishing"],
    a: "c",
    e: "Stagnant (adj.) means having no activity, progress, or growth; inactive.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["stagnant", "Inactive; lacking development."], ["vibrant", "Full of life and activity."]]
  },
  {
    i: 144,
    q: "The continuous dry heat caused the flowers to ______ and droop toward the soil.",
    c: ["flourish", "wilt", "germinate", "bloom", "blossom"],
    a: "b",
    e: "Wilt (v.) means to become limp through heat, loss of water, or disease; droop.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["wilt", "Droop and dry out."], ["germinate", "Begin to grow and sprout."]]
  },
  {
    i: 145,
    q: "To prove the validity of her scientific claim, the researcher must ______ her theory with concrete experimental data.",
    c: ["debunk", "invalidate", "corroborate", "subvert", "repudiate"],
    a: "c",
    e: "Corroborate (v.) means to confirm or give support to (a statement, theory, or finding).",
    d: "intermediate",
    t: "cause_effect",
    ch: 6,
    v: [["corroborate", "Confirm or support with evidence."], ["repudiate", "Refuse to accept; reject."]]
  },
  {
    i: 146,
    q: "The company's primary policy was to ______ its client list by building strong customer relationships.",
    c: ["dwindle", "expand", "curtail", "liquidate", "subvert"],
    a: "b",
    e: "Expand (v.) means to become or make larger or more extensive.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["expand", "Make larger or more extensive."], ["curtail", "Reduce in extent or quantity."]]
  },
  {
    i: 147,
    q: "His argument was entirely ______ , containing multiple logical fallacies and clear errors.",
    c: ["factual", "specious", "impeccable", "valid", "sound"],
    a: "b",
    e: "Specious (adj.) means superficially plausible, but actually wrong.",
    d: "intermediate",
    t: "restatement",
    ch: 6,
    v: [["specious", "Superficially true but actually false."]]
  },
  {
    i: 148,
    q: "The unexpected travel delay was merely a ______ inconvenience that did not disrupt their entire vacation plans.",
    c: ["chronic", "perpetual", "trivial", "catastrophic", "monumental"],
    a: "c",
    e: "Trivial (adj.) means of little value or importance.",
    d: "easy",
    t: "contrast",
    ch: 6,
    v: [["trivial", "Of little importance; minor."], ["chronic", "Persisting for a long time."]]
  },
  {
    i: 149,
    q: "The newly hired apprentice was so ______ that she learned the complex manufacturing process in single week.",
    c: ["obtuse", "sluggish", "apt", "indolent", "hostile"],
    a: "c",
    e: "Apt (adj.) means quick to learn; intelligent or suited.",
    d: "easy",
    t: "cause_effect",
    ch: 6,
    v: [["apt", "Quick to learn; intelligent."], ["indolent", "Wanting to avoid activity; lazy."]]
  },
  {
    i: 150,
    q: "The judge was widely praised for her ______ decisions, which were always completely free of personal bias.",
    c: ["arbitrary", "subjective", "equitable", "partial", "biased"],
    a: "c",
    e: "Equitable (adj.) means fair and impartial.",
    d: "intermediate",
    t: "cause_effect",
    ch: 6,
    v: [["equitable", "Fair and impartial."], ["arbitrary", "Based on random choice or whim."]]
  },

  // CHAPTER 7 (151 - 175)
  {
    i: 151,
    q: "When we first meet Romeo, he is ______ over his unrequited love for Rosaline.",
    c: ["brooding", "ogling", "meandering", "embellishing", "groveling"],
    a: "a",
    e: "To brood (v.) is to think deeply and moodily or anxiously about something.",
    d: "intermediate",
    t: "restatement",
    ch: 7,
    v: [["brooding", "Showing deep unhappiness of thought."]]
  },
  {
    i: 152,
    q: "Because it had been worn and washed so often, Linus’s favorite t-shirt was tattered and ______ with holes.",
    c: ["salvaged", "circulated", "riddled", "emulated", "congregated"],
    a: "c",
    e: "To riddle (v.) means to pierce with many holes; permeate thoroughly.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["riddled", "Filled or permeated with holes."]]
  },
  {
    i: 153,
    q: "Henley’s ______ remarks about my presentation did not bother me because I knew I’d done fine.",
    c: ["derogatory", "voracious", "tactile", "capricious", "amiable"],
    a: "a",
    e: "Derogatory (adj.) means showing a critical or disrespectful attitude; belittling.",
    d: "easy",
    t: "contrast",
    ch: 7,
    v: [["derogatory", "Showing critical or disrespectful attitude."]]
  },
  {
    i: 154,
    q: "Eels swim using a rapid ______ motion that propels them through the water.",
    c: ["dissipating", "undulating", "eradicating", "objurgating", "irritating"],
    a: "b",
    e: "Undulating (adj.) means moving with a smooth wavelike motion.",
    d: "advanced",
    t: "restatement",
    ch: 7,
    v: [["undulating", "Moving with a smooth wavelike motion."]]
  },
  {
    i: 155,
    q: "The ______ construction crew built large new buildings all over the East Coast, wherever work took them.",
    c: ["laconic", "irresolute", "itinerant", "parietal", "peremptory"],
    a: "c",
    e: "Itinerant (adj.) means traveling from place to place.",
    d: "advanced",
    t: "restatement",
    ch: 7,
    v: [["itinerant", "Traveling from place to place."]]
  },
  {
    i: 156,
    q: "The athlete's ______ flexibility allowed her to perform the gymnast routines with absolute ease.",
    c: ["limited", "sluggish", "supple", "rigid", "inflexible"],
    a: "c",
    e: "Supple (adj.) means bending, moving, or adapting easily; flexible.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["supple", "Bending easily; flexible."], ["rigid", "Inflexible or stiff."]]
  },
  {
    i: 157,
    q: "His speech was so ______ that it was impossible to follow the main thesis of his argument.",
    c: ["lucid", "coherent", "discursive", "explicit", "straightforward"],
    a: "c",
    e: "Discursive (adj.) means digressing from subject to subject; rambling.",
    d: "advanced",
    t: "cause_effect",
    ch: 7,
    v: [["discursive", "Digressing from subject to subject; rambling."], ["lucid", "Expressed clearly."]]
  },
  {
    i: 158,
    q: "The primary flaw in his logic was an assumption that was completely ______ by the final facts.",
    c: ["corroborated", "validated", "refuted", "substantiated", "supported"],
    a: "c",
    e: "Refuted (v.) means proved to be wrong or false; disproved.",
    d: "intermediate",
    t: "cause_effect",
    ch: 7,
    v: [["refuted", "Proved to be wrong or false."], ["corroborated", "Supported with evidence."]]
  },
  {
    i: 159,
    q: "Despite his success, he remained extremely ______ about his achievements, never boasting.",
    c: ["arrogant", "prejudiced", "modest", "egocentric", "pretentious"],
    a: "c",
    e: "Modest (adj.) means assuming or moderate in the estimation of one's achievements.",
    d: "easy",
    t: "contrast",
    ch: 7,
    v: [["modest", "Unassuming; moderate."], ["arrogant", "Haughty and self-important."]]
  },
  {
    i: 160,
    q: "The dry soil began to ______ after several weeks of gentle, steady rainfall.",
    c: ["desiccate", "wilt", "rejuvenate", "aridify", "solidify"],
    a: "c",
    e: "Rejuvenate (v.) means to make look or feel younger, fresher, or more lively.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["rejuvenate", "Restore to youthful vigor/freshness."], ["desiccate", "Dry out thoroughly."]]
  },
  {
    i: 161,
    q: "Rather than taking sides, the arbitrator remained completely ______ throughout the major labor dispute.",
    c: ["biased", "partial", "disinterested", "passionate", "prejudiced"],
    a: "c",
    e: "Disinterested (adj.) means not influenced by considerations of personal advantage; impartial/unbiased.",
    d: "intermediate",
    t: "contrast",
    ch: 7,
    v: [["disinterested", "Impartial; objective."], ["biased", "Unfairly prejudiced for or against."]]
  },
  {
    i: 162,
    q: "The continuous dry heat caused the flowers to ______ and droop toward the dirt.",
    c: ["blossom", "flourish", "wilt", "bloom", "germinate"],
    a: "c",
    e: "Wilt (v.) means to become limp through heat or lack of water; droop.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["wilt", "Droop and dry out."], ["germinate", "Begin to sprout and grow."]]
  },
  {
    i: 163,
    q: "He spent years in a state of complete ______ after his farm was ruined by the severe plague.",
    c: ["affluence", "vitality", "lethargy", "prosperity", "affability"],
    a: "c",
    e: "Lethargy (n.) is a lack of energy and enthusiasm.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["lethargy", "Lack of energy/sluggishness."], ["affluence", "Wealth; rich state."]]
  },
  {
    i: 164,
    q: "Unlike her sister who makes decisions quickly, Jane is incredibly ______.",
    c: ["decisive", "resolute", "indecisive", "rash", "impetuous"],
    a: "c",
    e: "Indecisive (adj.) means not providing a clear and definite result; hesitating.",
    d: "easy",
    t: "contrast",
    ch: 7,
    v: [["indecisive", "Unable to make choices quickly."] ]
  },
  {
    i: 165,
    q: "The speaker's message was so ______ that it was open to multiple interpretations.",
    c: ["lucid", "straightforward", "ambiguous", "concrete", "precise"],
    a: "c",
    e: "Ambiguous (adj.) means open to more than one interpretation; unclear.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["ambiguous", "Open to multiple interpretation."], ["lucid", "Clearly expressed; easy to understand."]]
  },
  {
    i: 166,
    q: "Scientific observation served to ______ the researcher's theory about natural division.",
    c: ["debunk", "invalidate", "substantiate", "subvert", "contradict"],
    a: "c",
    e: "Substantiate (v.) means to provide evidence to support or prove the truth of.",
    d: "intermediate",
    t: "cause_effect",
    ch: 7,
    v: [["substantiate", "Support with proof/evidence."], ["debunk", "Expose the falsehood of."]]
  },
  {
    i: 167,
    q: "The antique manuscript is extremely ______ and must be handled with protective cotton gloves.",
    c: ["robust", "durable", "fragile", "elastic", "flexible"],
    a: "c",
    e: "Fragile (adj.) means easily broken or damaged; delicate.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["fragile", "Delicate; easily broken."], ["robust", "Strong and sturdy."]]
  },
  {
    i: 168,
    q: "The manager's ______ comments deeply insulted several of the hard-working employees.",
    c: ["complimentary", "laudatory", "derogatory", "encouraging", "deferential"],
    a: "c",
    e: "Derogatory (adj.) means showing a critical or disrespectful attitude; disparaging.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["derogatory", "Disrespectful; belittling."], ["laudatory", "Expressing praise or commendation."]]
  },
  {
    i: 169,
    q: "The legal code is ______ ; all citizens must obey its regulations or face immediate legal fines.",
    c: ["optional", "compulsory", "superfluous", "ancillary", "discretionary"],
    a: "b",
    e: "Compulsory (adj.) means required by law or a rule; obligatory.",
    d: "easy",
    t: "restatement",
    ch: 7,
    v: [["compulsory", "Obligatory; required."], ["superfluous", "More than enough; unneeded."]]
  },
  {
    i: 170,
    q: "The ancient text was so ______ that only classical scholars could translate its true meaning.",
    c: ["lucid", "coherent", "obscure", "explicit", "evident"],
    a: "c",
    e: "Obscure (adj.) means not discovered or known about; uncertain or difficult to understand.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["obscure", "Difficult to understand; unknown."] ]
  },
  {
    i: 171,
    q: "Rather than providing a clear solution, the developer gave a ______ about technical excellence.",
    c: ["platitude", "revelation", "wisdom", "thesis", "insight"],
    a: "a",
    e: "A platitude (n.) is an overused moral remark or statement that lacks original thought.",
    d: "intermediate",
    t: "restatement",
    ch: 7,
    v: [["platitude", "Cliché; overused moral statement."]]
  },
  {
    i: 172,
    q: "Due to a lack of development, the local real estate market has been in a ______ state for three years.",
    c: ["dynamic", "stagnant", "prosperous", "flourishing", "escalating"],
    a: "b",
    e: "Stagnant (adj.) means showing no activity or growth; inactive.",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["stagnant", "Inactive; not developing."], ["dynamic", "Constant activity and progress."]]
  },
  {
    i: 173,
    q: "To prove her claim, she must ______ her argument with physical proof.",
    c: ["debunk", "invalidate", "corroborate", "subvert", "repudiate"],
    a: "c",
    e: "Corroborate (v.) means to confirm or give support to (a statement or theory).",
    d: "intermediate",
    t: "cause_effect",
    ch: 7,
    v: [["corroborate", "Support with evidence; confirm."], ["repudiate", "Reject; refuse to accept."]]
  },
  {
    i: 174,
    q: "The software was constructed to ______ efficiency by automating boring administrative tasks.",
    c: ["curtail", "dwindle", "optimize", "neutralize", "subvert"],
    a: "c",
    e: "Optimize (v.) means to make the best or most effective use of (a situation or resource).",
    d: "easy",
    t: "cause_effect",
    ch: 7,
    v: [["optimize", "Make best use of; improve."], ["curtail", "Reduce in extent or quantity."]]
  },
  {
    i: 175,
    q: "His presentation was entirely ______ , containing multiple factual errors and logical inconsistencies.",
    c: ["flawless", "erroneous", "factual", "valid", "impeccable"],
    a: "b",
    e: "Erroneous (adj.) means containing error; wrong or incorrect.",
    d: "easy",
    t: "restatement",
    ch: 7,
    v: [["erroneous", "Wrong; incorrect."], ["impeccable", "In accordance with highest standards; faultless."]]
  },

  // CHAPTER 8 (176 - 200)
  {
    i: 176,
    q: "A(n) ______ spirit only causes more stress and strife; it is better to forgive and forget.",
    c: ["apathetic", "restorative", "flaccid", "vindictive", "fortuitous"],
    a: "d",
    e: "Vindictive (adj.) means having or showing a strong desire for revenge.",
    d: "intermediate",
    t: "contrast",
    ch: 8,
    v: [["vindictive", "Spiteful; revenge-seeking."]]
  },
  {
    i: 177,
    q: "When we were renovating the old house, we found a ______ of bills hidden inside the laundry chute.",
    c: ["odyssey", "matrix", "lament", "fodder", "cache"],
    a: "e",
    e: "A cache (n.) is a collection of items of the same type stored in a hidden place.",
    d: "intermediate",
    t: "restatement",
    ch: 8,
    v: [["cache", "A hidden storage collection."]]
  },
  {
    i: 178,
    q: "Even though the pilot promised it was safe, Neil was ______ to fly during a heavy snowstorm.",
    c: ["habitual", "overzealous", "pavid", "reluctant", "salacious"],
    a: "d",
    e: "Reluctant (adj.) means unwilling and hesitant; disinclined.",
    d: "easy",
    t: "contrast",
    ch: 8,
    v: [["reluctant", "Unwilling and hesitant; disinclined."]]
  },
  {
    i: 179,
    q: "Ron has few friends because he is ______ and cares only about himself.",
    c: ["mundane", "intrepid", "garrulous", "voracious", "egocentric"],
    a: "e",
    e: "Egocentric (adj.) means thinking only of oneself, without regard for the feelings of others; self-centered.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["egocentric", "Self-centered; thinking only of oneself."]]
  },
  {
    i: 180,
    q: "The workers attempted to ______ the supervisor’s authority by negotiating terms directly with the clients.",
    c: ["contradict", "instigate", "resonate", "placate", "undermine"],
    a: "e",
    e: "To undermine (v.) means to damage or weaken the power or efficacy of, especially gradually.",
    d: "intermediate",
    t: "cause_effect",
    ch: 8,
    v: [["undermine", "Damage or weaken authority gradually."]]
  },
  {
    i: 181,
    q: "She maintained her ______ lifestyle, never spending more than was absolutely necessary.",
    c: ["lavish", "extravagant", "frugal", "profligate", "generous"],
    a: "c",
    e: "Frugal (adj.) means sparing or economical with regard to money or food.",
    d: "easy",
    t: "restatement",
    ch: 8,
    v: [["frugal", "Economical; sparing with resources."], ["lavish", "Sumptuously rich, elaborate, or luxurious."]]
  },
  {
    i: 182,
    q: "The speaker's explanations were extremely ______ , using clear examples and simple language.",
    c: ["convoluted", "abstruse", "lucid", "obscure", "opaque"],
    a: "c",
    e: "Lucid (adj.) means expressed clearly; easy to understand.",
    d: "easy",
    t: "restatement",
    ch: 8,
    v: [["lucid", "Clear and easy to understand."], ["abstruse", "Difficult to understand; obscure."]]
  },
  {
    i: 183,
    q: "The new medication had a ______ effect on his health, restoring his regular energy levels.",
    c: ["detrimental", "salutary", "toxic", "neutral", "insignificant"],
    a: "b",
    e: "Salutary (adj.) means producing good effects; beneficial or health-promoting.",
    d: "intermediate",
    t: "cause_effect",
    ch: 8,
    v: [["salutary", "Beneficial; health-promoting."], ["detrimental", "Tending to cause harm."]]
  },
  {
    i: 184,
    q: "Unlike his sister who is highly gregarious, Donald has a very ______ personality.",
    c: ["social", "extroverted", "reserved", "convivial", "garrulous"],
    a: "c",
    e: "Reserved (adj.) means slow to reveal emotion or opinions; quiet or private.",
    d: "easy",
    t: "contrast",
    ch: 8,
    v: [["reserved", "Quiet; slow to show emotion."], ["convivial", "Friendly, lively, and enjoyable."]]
  },
  {
    i: 185,
    q: "The researcher found many ______ historical records that contradicted the standard narrative.",
    c: ["verified", "authentic", "apocryphal", "supported", "factual"],
    a: "c",
    e: "Apocryphal (adj.) means of doubtful authenticity, although widely circulated as true.",
    d: "intermediate",
    t: "cause_effect",
    ch: 8,
    v: [["apocryphal", "Doubtful authenticity; fictitious."], ["factual", "Concerned with what is actually the case."]]
  },
  {
    i: 186,
    q: "The continuous dry heat has caused the moisture in the topsoil to ______.",
    c: ["expand", "condense", "dissipate", "saturate", "overflow"],
    a: "c",
    e: "Dissipate (v.) means to disappear or cause to disappear; disperse or dry up.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["dissipate", "Disperse; disappear gradually."], ["saturate", "Make thoroughly wet."]]
  },
  {
    i: 187,
    q: "His argument was entirely ______ , based on multiple unproven assumptions and logical errors.",
    c: ["sound", "empirical", "fallacious", "proven", "valid"],
    a: "c",
    e: "Fallacious (adj.) means based on a mistaken belief; logically unsound.",
    d: "easy",
    t: "restatement",
    ch: 8,
    v: [["fallacious", "Mistaken; logically unsound."], ["empirical", "Based on verifiable observation."]]
  },
  {
    i: 188,
    q: "The newly hired architect was very ______ , easily adapting her designs to meet safety standards.",
    c: ["inflexible", "obstinate", "pliant", "rigid", "headstrong"],
    a: "c",
    e: "Pliant (adj.) means easily bent or flexible; adaptable or yielding.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["pliant", "Flexible; easily adaptable."], ["obstinate", "Stubbornly refusing to change."]]
  },
  {
    i: 189,
    q: "The children became ______ after spending hours reading by the warm fireplace.",
    c: ["hyperactive", "sleepy", "somnolent", "vigilant", "insentient"],
    a: "c",
    e: "Somnolent (adj.) means sleepy or drowsy.",
    d: "intermediate",
    t: "cause_effect",
    ch: 8,
    v: [["somnolent", "Sleepy or drowsy."], ["vigilant", "Keeping careful watch for danger."]]
  },
  {
    i: 190,
    q: "The historic museum displays many ______ artifacts representing early Native groups.",
    c: ["imported", "modern", "indigenous", "contemporary", "futuristic"],
    a: "c",
    e: "Indigenous (adj.) means originating or occurring naturally in a particular place; native.",
    d: "easy",
    t: "restatement",
    ch: 8,
    v: [["indigenous", "Native to a specific region."], ["contemporary", "Living or occurring at the same time."]]
  },
  {
    i: 191,
    q: "In contrast to Marcus's generally morose behavior, Julian is always extremely ______.",
    c: ["sullen", "ebullient", "glum", "gloom", "reserved"],
    a: "b",
    e: "Ebullient (adj.) means cheerful and full of energy; exuberant.",
    d: "easy",
    t: "contrast",
    ch: 8,
    v: [["ebullient", "Exuberantly cheerful/energetic."], ["sullen", "Bad-tempered and sulky."]]
  },
  {
    i: 192,
    q: "Because her accounts were known for perfect ______ , no one doubted Jane’s testimony.",
    c: ["guile", "mendacity", "veracity", "cupidity", "artifice"],
    a: "c",
    e: "Veracity (n.) is conformity to facts; accuracy or truthfulness.",
    d: "intermediate",
    t: "cause_effect",
    ch: 8,
    v: [["veracity", "Truthfulness; accuracy."], ["mendacity", "Lying; untruthfulness."]]
  },
  {
    i: 193,
    q: "The mountain trail was structurally ______ due to the recent rainstorm and mud slides.",
    c: ["sound", "durable", "precarious", "robust", "safe"],
    a: "c",
    e: "Precarious (adj.) means not securely held; dangerously unstable or unsafe.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["precarious", "Dangerously unstable; unsafe."], ["sound", "In good condition; robust."]]
  },
  {
    i: 194,
    q: "Rather than giving a direct answer, the witness gave an ______ response that frustrated the judge.",
    c: ["lucid", "evasive", "explicit", "candid", "transparent"],
    a: "b",
    e: "Evasive (adj.) means tending to avoid commitment or response, especially by responding indirectly.",
    d: "easy",
    t: "contrast",
    ch: 8,
    v: [["evasive", "Avoiding direct commitment; slippery."], ["candid", "Frank and honest."]]
  },
  {
    i: 195,
    q: "The business failed due to the directors’ public reputation for ______ and greed.",
    c: ["probity", "frugality", "avarice", "generosity", "benevolence"],
    a: "c",
    e: "Avarice (n.) is extreme greed for wealth or material gain.",
    d: "intermediate",
    t: "cause_effect",
    ch: 8,
    v: [["avarice", "Extreme greed for wealth."], ["probity", "Having strong honesty/integrity."]]
  },
  {
    i: 196,
    q: "The judge was praised for her ______ decisions, which were always completely free of bias.",
    c: ["biased", "partial", "equitable", "arbitrary", "subjective"],
    a: "c",
    e: "Equitable (adj.) means fair and impartial.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["equitable", "Fair and impartial."], ["arbitrary", "Based on random whim rather than law."]]
  },
  {
    i: 197,
    q: "The computer interface was designed to be ______ so that users could navigate it without training.",
    c: ["intuitive", "convoluted", "abstruse", "obscure", "rigid"],
    a: "a",
    e: "Intuitive (adj.) means easy to use and understand without explicit instruction.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["intuitive", "Easy to understand immediately."], ["abstruse", "Difficult to understand; obscure."]]
  },
  {
    i: 198,
    q: "His speeches were filled with meaningless ______ that added little of substance to the debate.",
    c: [" sabiduría", "rhetoric", "coherence", "conciseness", "brevity"],
    a: "b",
    e: "Rhetoric (n.) is language designed to have a persuasive effect, but which is often seen as lacking substance.",
    d: "easy",
    t: "restatement",
    ch: 8,
    v: [["rhetoric", "Persuasive language lacking substance."]]
  },
  {
    i: 199,
    q: "The dry wind caused the lake level to ______ significantly during the summer.",
    c: ["overflow", "expand", "subside", "saturate", "oscillate"],
    a: "c",
    e: "Subside (v.) means to sink or settle down to a lower or less active level.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["subside", "Go down to a lower level; sink."], ["oscillate", "Move/swing back and forth."]]
  },
  {
    i: 200,
    q: "The young student was so ______ that she learned the classical language in single semester.",
    c: ["obtuse", "indolent", "apt", "negligent", "sluggish"],
    a: "c",
    e: "Apt (adj.) means quick to learn; suited or intelligent.",
    d: "easy",
    t: "cause_effect",
    ch: 8,
    v: [["apt", "Quick to learn; suited."], ["indolent", "Wanting to avoid activity; lazy."]]
  }
];
