import { WordBlock } from './types';

export const VOCABULARY_DATA: WordBlock[] = [
  {
    id: 'block1',
    title: 'Block 1: A – AM',
    words: [
      { word: 'Abate', context: 'Intensity/Weather', definition: 'To decrease or die down.', nuance: 'It describes something powerful (like a storm or a fever) getting weaker.', example: 'We waited for the wind to abate before going outside.' },
      { word: 'Aberrant', context: 'Science/Behavior', definition: 'Abnormal.', nuance: 'It implies a weird departure from the "right" path.', example: 'The scientist was worried by the aberrant results of the blood test.' },
      { word: 'Abeyance', context: 'Legal/Formal', definition: 'Temporary suspension.', nuance: 'Things are "on ice" until a decision is made.', example: 'The property deal was held in abeyance until the taxes were paid.' },
      { word: 'Abscond', context: 'Crime', definition: 'To run away and hide.', nuance: 'Usually implies taking stolen money or avoiding arrest.', example: "The accountant absconded with the company's millions." },
      { word: 'Abstemious', context: 'Lifestyle', definition: 'Eating/drinking very little.', nuance: 'It’s about self-discipline and moderation.', example: 'He remained abstemious even at the party, drinking only water.' },
      { word: 'Admonish', context: 'Authority', definition: 'To warn or scold gently.', nuance: "It's a firm talking to, not a screaming match.", example: 'The teacher admonished the students for being late.' },
      { word: 'Adulterate', context: 'Quality', definition: 'To make something worse by adding cheap stuff.', nuance: 'Usually used for food, chemicals, or wine.', example: 'The olive oil was adulterated with cheap vegetable oil.' },
      { word: 'Aesthetic', context: 'Art/Beauty', definition: 'Related to visual appeal.', nuance: 'The "look and feel" of something.', example: 'The building’s aesthetic was modern and minimalist.' },
      { word: 'Aggregate', context: 'Math/Total', definition: 'A whole formed by combining several parts.', nuance: 'The "grand total" of many different things.', example: 'The aggregate score of the two games was 4-1.' },
      { word: 'Alacrity', context: 'Attitude', definition: 'Cheerful readiness.', nuance: 'Doing something fast because you want to do it.', example: 'She accepted the job offer with alacrity.' },
      { word: 'Alleviate', context: 'Pain/Problems', definition: 'To make suffering more bearable.', nuance: "It doesn't cure the problem; it just makes it hurt less.", example: 'Take an aspirin to alleviate your headache.' },
      { word: 'Amalgamate', context: 'Business/Chemistry', definition: 'To combine into one.', nuance: 'Two separate things becoming one single body.', example: 'The two small banks amalgamated to form a giant corporation.' },
      { word: 'Ambiguous', context: 'Communication', definition: 'Unclear because there are two meanings.', nuance: "It's confusing because the message is vague.", example: 'His ambiguous reply left me wondering if he was coming or not.' },
      { word: 'Ambivalence', context: 'Emotions', definition: 'Having mixed feelings.', nuance: 'You like it and hate it at the same time.', example: 'She felt ambivalence about moving; she loved the new job but hated leaving her friends.' },
      { word: 'Ameliorate', context: 'Bad situations', definition: 'To make something better.', nuance: 'You "fix" a bad situation (like poverty or health).', example: 'The new law was intended to ameliorate living conditions in the slums.' }
    ]
  },
  {
    id: 'block2',
    title: 'Block 2: AN – AU',
    words: [
      { word: 'Anachronism', context: 'History/Time', definition: 'Something out of its proper time.', example: 'Seeing a digital watch in a movie about the 1700s is an anachronism.' },
      { word: 'Analogous', context: 'Logic', definition: 'Comparable or similar.', example: "A computer’s brain is analogous to the human brain." },
      { word: 'Anarchy', context: 'Politics', definition: 'A state of disorder due to no government.', example: 'When the police went on strike, the city fell into anarchy.' },
      { word: 'Anomalous', context: 'Data/Science', definition: 'Unusual or unexpected.', nuance: 'A "glitch" in the normal pattern.', example: 'An anomalous warm day in the middle of winter.' },
      { word: 'Antipathy', context: 'Social', definition: 'A deep-seated feeling of dislike.', example: 'There has always been a strong antipathy between the two rival teams.' },
      { word: 'Apathy', context: 'Social', definition: 'Lack of interest or concern.', nuance: 'Not caring enough to even have an opinion.', example: "Voter apathy is high because people don't think their vote matters." },
      { word: 'Appease', context: 'Conflict', definition: 'To calm someone by giving them what they want.', nuance: 'Often has a negative flavor (giving in to a bully).', example: 'They tried to appease the angry customer with a full refund.' },
      { word: 'Apprise', context: 'Formal Info', definition: 'To inform someone.', example: 'Please apprise me of any changes to the schedule.' },
      { word: 'Approbation', context: 'Formal', definition: 'Approval or praise.', example: "The opera singer's performance was met with loud approbation." },
      { word: 'Appropriate', context: 'Action', definition: "To take something for one's own use without permission.", example: 'The government appropriated the land to build a highway.' },
      { word: 'Arduous', context: 'Work', definition: 'Difficult and tiring.', nuance: 'Requires a long, exhausting effort.', example: 'The hike up the mountain was an arduous six-hour journey.' },
      { word: 'Artless', context: 'Personality', definition: 'Natural, simple, and honest.', nuance: 'No "acting" or "tricks" involved.', example: 'Her artless beauty and simple manners charmed everyone.' },
      { word: 'Ascetic', context: 'Religion/Lifestyle', definition: 'Living without luxury for spiritual reasons.', example: 'The monk lived an ascetic life in a small cave.' },
      { word: 'Assiduous', context: 'Work habit', definition: 'Showing great care and perseverance.', nuance: 'Hardworking and paying attention to every detail.', example: 'She was assiduous in her research, checking every fact twice.' },
      { word: 'Assuage', context: 'Feelings', definition: 'To make an unpleasant feeling less intense.', nuance: 'To soothe guilt, fear, or hunger.', example: 'He sent flowers to assuage his guilt for forgetting her birthday.' },
      { word: 'Attenuate', context: 'Science/Force', definition: 'To weaken or thin out.', example: 'Earplugs will attenuate the loud noise of the machines.' },
      { word: 'Audacious', context: 'Risks', definition: 'Extremely bold or daring.', nuance: 'Can be "brave" or "rudely bold."', example: 'The bank robbery was an audacious plan carried out in broad daylight.' },
      { word: 'Austere', context: 'Style/Life', definition: 'Simple, strict, and without luxury.', example: 'The prison cell was austere, containing only a bed and a sink.' },
      { word: 'Aver', context: 'Legal/Speech', definition: 'To state something as a fact.', example: 'The witness averred that she had seen the suspect at the scene.' }
    ]
  },
  {
    id: 'block3',
    title: 'Block 3: B – C',
    words: [
      { word: 'Banal', context: 'Ideas', definition: 'Boring and unoriginal.', nuance: "So common that it's uninteresting.", example: 'The movie had a banal plot that we’ve seen a thousand times.' },
      { word: 'Belie', context: 'Appearance', definition: 'To give a false impression.', example: 'His calm face belied the anger he was feeling inside.' },
      { word: 'Beneficent', context: 'Character', definition: 'Doing good; generous.', example: 'The school was built by a beneficent anonymous donor.' },
      { word: 'Bolster', context: 'Support', definition: 'To strengthen or support.', example: 'She used statistics to bolster her argument.' },
      { word: 'Bombastic', context: 'Speech', definition: 'High-sounding words with little meaning.', nuance: 'Someone trying to sound smart but being "full of hot air."', example: "The politician's bombastic speech didn't actually promise anything." },
      { word: 'Boorish', context: 'Manners', definition: 'Rude and insensitive.', example: 'His boorish behavior at the dinner table embarrassed his wife.' },
      { word: 'Burgeon', context: 'Growth', definition: 'To grow or flourish quickly.', example: "The town's economy burgeoned after the new factory opened." },
      { word: 'Burnish', context: 'Surface/Reputation', definition: 'To polish and make shiny.', example: 'He worked hard to burnish his image before the election.' },
      { word: 'Buttress', context: 'Structure/Logic', definition: 'A support or reinforcement.', example: 'The lawyer presented new evidence to buttress her case.' },
      { word: 'Cacophonous', context: 'Sound', definition: 'Harsh and unpleasant sounding.', example: 'The cacophonous noise of the construction site made it impossible to sleep.' },
      { word: 'Capricious', context: 'Personality', definition: 'Given to sudden changes of mood or behavior.', nuance: 'Unpredictable and impulsive.', example: 'The weather here is capricious; it’s sunny one minute and raining the next.' },
      { word: 'Castigation', context: 'Discipline', definition: 'Severe criticism or punishment.', example: 'The coach’s castigation of the players was overheard by everyone in the locker room.' },
      { word: 'Catalyst', context: 'Change', definition: 'Something that starts a process.', example: 'The assassination was the catalyst for the war.' },
      { word: 'Caustic', context: 'Chemistry/Tone', definition: 'Sarcastic in a biting or stinging way.', nuance: 'Words that "burn" the listener.', example: 'She made a caustic remark about his cheap suit.' },
      { word: 'Chicanery', context: 'Politics/Law', definition: 'The use of trickery to achieve a purpose.', example: 'He used political chicanery to get the law passed.' },
      { word: 'Coagulate', context: 'Liquid', definition: 'To change from liquid to solid (like blood).', example: 'The blood began to coagulate around the wound.' },
      { word: 'Coda', context: 'Music/Literature', definition: 'A concluding part of a story or song.', example: "The book’s final chapter serves as a moving coda to the hero's life." },
      { word: 'Cogent', context: 'Argument', definition: 'Clear, logical, and convincing.', example: 'She made a cogent argument for why the company should go green.' },
      { word: 'Commensurate', context: 'Size/Degree', definition: 'Proportional; equal in measure.', example: 'Your salary will be commensurate with your experience.' },
      { word: 'Compendium', context: 'Books', definition: 'A collection of detailed information about a subject.', example: 'The book is a compendium of all the plants found in the rainforest.' },
      { word: 'Complaisant', context: 'Personality', definition: 'Eager to please others.', nuance: 'Very cooperative and agreeable.', example: 'She was too complaisant, always saying yes even when she was overworked.' },
      { word: 'Compliant', context: 'Rules', definition: 'Obeying rules or requests.', example: 'The company was fully compliant with all safety regulations.' },
      { word: 'Conciliatory', context: 'Conflict', definition: 'Intended to end an argument and make peace.', example: 'He made a conciliatory gesture by offering an apology.' },
      { word: 'Condone', context: 'Ethics', definition: 'To accept or allow (usually bad behavior) to continue.', example: 'The school does not condone bullying of any kind.' },
      { word: 'Confound', context: 'Mind', definition: 'To surprise or confuse someone.', example: "The magician’s trick confounded the entire audience." },
      { word: 'Connoisseur', context: 'Art/Food', definition: 'An expert judge in matters of taste.', example: 'He is a connoisseur of fine Italian wines.' },
      { word: 'Contention', context: 'Debate', definition: 'A heated disagreement or a point being argued.', example: 'It is my contention that the new law will actually increase crime.' },
      { word: 'Contentious', context: 'Topic', definition: 'Causing an argument.', example: 'Abortion is a very contentious issue in many countries.' },
      { word: 'Contrite', context: 'Emotion', definition: 'Feeling very sorry for a sin or mistake.', example: 'He looked truly contrite as he apologized for the accident.' },
      { word: 'Conundrum', context: 'Logic', definition: 'A confusing and difficult problem or puzzle.', example: 'The mystery of how the thief escaped remains a conundrum.' },
      { word: 'Converge', context: 'Movement', definition: 'To come together from different directions.', example: 'The two rivers converge just outside the city.' },
      { word: 'Convoluted', context: 'Complexity', definition: 'Extremely complex and difficult to follow.', example: 'The movie had such a convoluted plot that I gave up trying to understand it.' },
      { word: 'Craven', context: 'Bravery', definition: 'Cowardly to a pathetic degree.', example: 'The craven soldier ran away while his friends stayed to fight.' }
    ]
  },
  {
    id: 'block4',
    title: 'Block 4: D – E',
    words: [
      { word: 'Daunt', context: 'Emotion', definition: 'To make someone feel intimidated or discouraged.', example: 'The size of the task did not daunt her; she started working immediately.' },
      { word: 'Decorum', context: 'Social', definition: 'Behavior that is controlled, calm, and polite.', example: 'The judge insisted on strict decorum in the courtroom.' },
      { word: 'Default', context: 'Finance/Computer', definition: 'Failure to act, or a pre-set option.', example: 'He defaulted on his loan payments and lost his car.' },
      { word: 'Deference', context: 'Social', definition: 'Humble submission and respect.', example: 'The young doctor showed deference to the experienced surgeon.' },
      { word: 'Delineate', context: 'Planning', definition: 'To describe or portray something precisely.', example: 'The architect delineated the boundaries of the property on the map.' },
      { word: 'Denigrate', context: 'Reputation', definition: 'To criticize unfairly; to "trash-talk."', example: "It is wrong to denigrate someone's hard work just because you are jealous." },
      { word: 'Deride', context: 'Social', definition: 'To laugh at someone in a mean, mocking way.', example: "The critics derided the actor’s poor performance." },
      { word: 'Derivative', context: 'Art/Finance', definition: 'Unoriginal; taken from something else.', example: 'His style of painting is very derivative of Picasso.' },
      { word: 'Desiccate', context: 'Physical', definition: 'To dry out completely.', example: 'The hot sun desiccated the crops.' },
      { word: 'Desultory', context: 'Action', definition: 'Lacking a plan, purpose, or enthusiasm.', nuance: 'Jumping from one thing to another randomly.', example: 'He had a desultory conversation with his neighbor while waiting for the bus.' },
      { word: 'Deterrent', context: 'Safety', definition: 'Something that discourages an action.', example: 'The cameras are a deterrent to shoplifters.' },
      { word: 'Diatribe', context: 'Speech', definition: 'A long, forceful, and bitter verbal attack.', example: 'The manager launched into a diatribe against the lazy staff.' },
      { word: 'Dichotomy', context: 'Logic', definition: 'A division between two things that are opposite.', example: 'There is a dichotomy between what he says and what he actually does.' },
      { word: 'Diffidence', context: 'Personality', definition: 'Modesty or shyness resulting from a lack of self-confidence.', example: 'Despite his success, he still spoke with a certain diffidence.' },
      { word: 'Diffuse', context: 'Physical/Speech', definition: 'Spread out over a large area; wordy.', example: 'The crowd was diffuse, scattered across the entire park.' },
      { word: 'Digression', context: 'Speech', definition: 'Wandering away from the main topic.', example: 'After a long digression about his childhood, the speaker got back to the point.' },
      { word: 'Dirge', context: 'Music', definition: 'A mourning song for the dead.', example: 'The wind howling through the trees sounded like a funeral dirge.' },
      { word: 'Disabuse', context: 'Mind', definition: 'To persuade someone that an idea is mistaken.', nuance: '"Setting someone straight."', example: 'I had to disabuse him of the notion that he could pass without studying.' },
      { word: 'Discerning', context: 'Judgment', definition: 'Having or showing good judgment.', example: 'A discerning art collector can spot a fake from a mile away.' },
      { word: 'Discordant', context: 'Sound/Social', definition: 'Lacking harmony; disagreeing.', example: 'The meeting ended on a discordant note with no agreement reached.' },
      { word: 'Discredit', context: 'Reputation', definition: 'To harm the good reputation of someone.', example: 'The scandalous photos were leaked to discredit the politician.' },
      { word: 'Discrepancy', context: 'Math/Logic', definition: 'An illogical lack of compatibility between two facts.', example: 'There is a discrepancy between his bank statement and his actual cash.' },
      { word: 'Discrete', context: 'Science/Logic', definition: 'Individually separate and distinct.', nuance: 'Do not confuse with "discreet" (secretive).', example: 'The machine is made of many discrete parts.' },
      { word: 'Disingenuous', context: 'Personality', definition: 'Not candid or sincere; pretending to know less than one does.', example: "It was disingenuous of him to say he didn't know about the party he helped plan." },
      { word: 'Disinterested', context: 'Law/Judging', definition: 'Not influenced by personal interest; unbiased.', example: 'We need a disinterested third party to settle this argument.' },
      { word: 'Disjointed', context: 'Communication', definition: 'Lacking a coherent connection; disconnected.', example: "The patient’s speech was disjointed and hard to follow." },
      { word: 'Dismiss', context: 'General', definition: 'To treat as unworthy of serious consideration.', example: 'She dismissed his ideas as old-fashioned.' },
      { word: 'Disparage', context: 'Social', definition: 'To regard or represent as being of little worth.', example: 'Never disparage your own achievements; you worked hard for them.' },
      { word: 'Disparate', context: 'Comparison', definition: 'Essentially different in kind.', example: 'They have disparate views on how to raise children.' },
      { word: 'Dissemble', context: 'Personality', definition: "To hide one's real feelings or beliefs.", example: 'She smiled to dissemble her true disappointment.' },
      { word: 'Disseminate', context: 'Information', definition: 'To spread info widely.', example: 'The internet allows us to disseminate news instantly.' },
      { word: 'Dissolution', context: 'Formal', definition: 'The closing down or dismissal of an assembly or partnership.', example: 'The dissolution of their marriage was final last week.' },
      { word: 'Dissonance', context: 'Sound/Mind', definition: 'A lack of harmony or agreement.', example: 'There is a dissonance between her words and her actions.' },
      { word: 'Distend', context: 'Physical', definition: 'To swell or cause to swell by pressure from inside.', example: 'Starving children often have stomachs that distend.' },
      { word: 'Distill', context: 'Science/Logic', definition: 'To extract the most important aspects of something.', example: 'He managed to distill the entire book into a one-page summary.' },
      { word: 'Diverge', context: 'Movement', definition: 'To move in different directions from a common point.', example: 'The two career paths diverge after the first year of training.' },
      { word: 'Divest', context: 'Business', definition: 'To strip or deprive someone of property or rights.', example: 'The company was forced to divest itself of its energy division.' },
      { word: 'Document', context: 'Action', definition: 'To record something in written or other form.', example: 'The case was well documented.' },
      { word: 'Dogmatic', context: 'Beliefs', definition: 'Laying down principles as undeniably true.', nuance: 'Being "bossy" about your opinions.', example: 'He is so dogmatic that he refuses to listen to any other opinions.' },
      { word: 'Dormant', context: 'Science/Nature', definition: 'Inactive; as though asleep.', example: 'The volcano has been dormant for hundreds of years.' },
      { word: 'Dupe', context: 'Action', definition: 'To trick or deceive.', example: 'The salesman duped the old lady into buying a broken car.' },
      { word: 'Ebullient', context: 'Emotion', definition: 'Cheerful and full of energy.', example: 'The ebullient fans cheered as their team scored the winning goal.' },
      { word: 'Eclectic', context: 'Style', definition: 'Deriving ideas or style from a broad and diverse range of sources.', example: 'Her house has an eclectic mix of antique and modern furniture.' },
      { word: 'Efficacy', context: 'Medicine/Action', definition: 'The ability to produce a desired result.', example: 'Scientists are testing the efficacy of the new vaccine.' },
      { word: 'Effrontery', context: 'Social', definition: 'Insolent or impertinent behavior; "nerve."', example: 'He had the effrontery to ask for a raise after being late every day.' },
      { word: 'Elegy', context: 'Literature', definition: 'A poem of serious reflection, typically a lament for the dead.', example: 'He wrote an elegy for his late friend.' },
      { word: 'Elicit', context: 'Action', definition: 'To evoke or draw out a response from someone.', example: "The comedian’s jokes failed to elicit even a single laugh." },
      { word: 'Embellish', context: 'Art/Speech', definition: 'To make something more attractive by adding decorative details (often fake ones).', example: 'He tended to embellish his war stories to make himself look like a hero.' },
      { word: 'Empirical', context: 'Science', definition: 'Based on observation or experience rather than theory.', example: 'We need empirical evidence before we can prove the theory.' },
      { word: 'Emulate', context: 'Social', definition: 'To match or surpass a person or achievement, typically by imitation.', example: "He hoped to emulate his father's success in business." },
      { word: 'Endemic', context: 'Science/Social', definition: 'Regularly found among particular people or in a certain area.', example: 'Malaria is endemic in some tropical regions.' },
      { word: 'Enervate', context: 'Physical', definition: 'To cause someone to feel drained of energy or vitality.', example: 'The hot sun enervated the marathon runners.' },
      { word: 'Engender', context: 'Cause/Effect', definition: 'To cause or give rise to a feeling, situation, or condition.', example: "The minister's speech engendered a sense of hope in the crowd." },
      { word: 'Enhance', context: 'General', definition: 'To improve the quality or value of.', example: 'Technology can enhance learning.' },
      { word: 'Ephemeral', context: 'Time', definition: 'Lasting for a very short time.', example: 'The beauty of a sunset is ephemeral.' },
      { word: 'Equanimity', context: 'Emotion', definition: 'Mental calmness and composure, especially in a difficult situation.', example: 'She handled the crisis with perfect equanimity.' },
      { word: 'Equivocate', context: 'Speech', definition: 'To use ambiguous language so as to conceal the truth.', example: 'When asked about the missing money, the manager began to equivocate.' },
      { word: 'Erudite', context: 'Personality', definition: 'Having or showing great knowledge or learning.', example: 'The erudite professor could speak ten different languages.' },
      { word: 'Esoteric', context: 'Knowledge', definition: 'Intended for or likely to be understood by only a small number of people with specialized knowledge.', example: 'The debate was over an esoteric point of law that no one else cared about.' },
      { word: 'Eulogy', context: 'Formal', definition: 'A speech that praises someone highly, typically someone who has just died.', example: 'The eulogy was deeply moving.' },
      { word: 'Euphemism', context: 'Speech', definition: 'A mild or indirect word substituted for one considered to be too harsh or blunt.', example: "‘Passed away’ is a euphemism for ‘died.’" },
      { word: 'Exacerbate', context: 'Situation', definition: 'To make a problem or bad situation worse.', example: 'Scratching the insect bite will only exacerbate the itch.' },
      { word: 'Exculpate', context: 'Legal', definition: 'To show or declare that someone is not guilty of wrongdoing.', example: 'The DNA evidence served to exculpate the man who had been in prison for years.' },
      { word: 'Exigency', context: 'Situation', definition: 'An urgent need or demand.', example: 'The exigencies of the war required everyone to work extra hours.' },
      { word: 'Extrapolation', context: 'Math/Logic', definition: 'Predicting the future by looking at current trends.', example: 'Based on an extrapolation of current sales, we will be rich by next year.' }
    ]
  },
  {
    id: 'block5',
    title: 'Block 5: F – G',
    words: [
      { word: 'Facetious', context: 'Social', definition: 'Treating serious issues with inappropriate humor.', example: "I’m being serious, so please stop making facetious remarks." },
      { word: 'Facilitate', context: 'Action', definition: 'To make an action or process easy or easier.', example: 'The new software will facilitate the booking process.' },
      { word: 'Fallacious', context: 'Logic', definition: 'Based on a mistaken belief or unsound argument.', example: 'The idea that you can get rich without working is fallacious.' },
      { word: 'Fatuous', context: 'Personality', definition: 'Silly and pointless.', example: 'He made a fatuous comment about the weather during the serious meeting.' },
      { word: 'Fawning', context: 'Social', definition: 'Displaying exaggerated flattery or affection (kissing up).', example: 'The celebrity was surrounded by fawning fans.' },
      { word: 'Felicitous', context: 'Speech/Style', definition: 'Well-chosen or suited to the circumstances.', example: 'He handled the delicate situation in a felicitous manner.' },
      { word: 'Fervor', context: 'Emotion', definition: 'Intense and passionate feeling.', example: 'He spoke with great fervor.' },
      { word: 'Flag', context: 'Energy', definition: 'To become tired, weaker, or less enthusiastic.', example: 'Towards the end of the race, his energy began to flag.' },
      { word: 'Fledgling', context: 'Status', definition: 'A person or organization that is immature, inexperienced, or undeveloped.', example: 'The fledgling company is still looking for its first customer.' },
      { word: 'Flout', context: 'Rules', definition: 'To openly disregard a rule or law.', example: 'They flouted the law by drinking in public.' },
      { word: 'Foment', context: 'Conflict', definition: 'To stir up trouble or violence.', example: 'The rebels tried to foment a revolution among the farmers.' },
      { word: 'Forestall', context: 'Action', definition: 'To prevent or obstruct an anticipated event by taking action ahead of time.', example: 'The government took steps to forestall an economic crisis.' },
      { word: 'Frugality', context: 'Money', definition: 'The quality of being economical with money or food.', example: 'He is known for his frugality.' },
      { word: 'Futile', context: 'Effort', definition: 'Pointless; producing no result.', example: 'It is futile to try to reason with him when he is this angry.' },
      { word: 'Gainsay', context: 'Formal', definition: 'To deny or contradict a fact or statement.', example: 'No one can gainsay the fact that she is the best player on the team.' },
      { word: 'Garrulous', context: 'Social', definition: 'Excessively talkative, especially on trivial matters.', example: 'The garrulous neighbor kept me at the door for an hour.' },
      { word: 'Goad', context: 'Action', definition: 'To provoke or annoy someone into doing something.', example: 'She goaded him into losing his temper.' },
      { word: 'Gouge', context: 'Money', definition: 'To overcharge someone swindlingly.', example: 'The gas station was accused of gouging prices during the hurricane.' },
      { word: 'Grandiloquent', context: 'Speech', definition: 'Pompous or extravagant in language, style, or manner.', nuance: 'Using big words to sound important.', example: 'His grandiloquent speech bored the audience.' },
      { word: 'Gregarious', context: 'Personality', definition: 'Fond of company; sociable.', example: 'He is a gregarious person who loves parties.' },
      { word: 'Guileless', context: 'Personality', definition: 'Devoid of guile; innocent and without deception.', example: 'Her guileless smile won everyone over.' },
      { word: 'Gullible', context: 'Personality', definition: 'Easily persuaded to believe something.', example: 'He is so gullible he believed the prank.' }
    ]
  },
  {
    id: 'block6',
    title: 'Block 6: H – I',
    words: [
      { word: 'Harangue', context: 'Speech', definition: 'A lengthy and aggressive speech.', example: 'The protesters were subjected to a two-hour harangue.' },
      { word: 'Homogenous', context: 'Science/Group', definition: 'Of the same kind; alike.', example: 'The town has a homogenous population.' },
      { word: 'Hyperbole', context: 'Speech', definition: 'Exaggerated statements not meant to be taken literally.', example: 'I’m so hungry I could eat a horse is a classic hyperbole.' },
      { word: 'Iconoclast', context: 'Personality', definition: 'A person who attacks cherished beliefs or institutions.', example: 'As an iconoclast, he delighted in challenging the church\'s rules.' },
      { word: 'Idolatry', context: 'Religion/Social', definition: 'Extreme admiration, love, or reverence for something or someone.', example: 'His idolatry of the pop star was borderline obsessive.' },
      { word: 'Immutable', context: 'Logic', definition: 'Unchanging over time or unable to be changed.', example: 'The laws of physics are immutable.' },
      { word: 'Impair', context: 'General', definition: 'To weaken or damage something (especially a human faculty).', example: 'Smoking can impair your health.' },
      { word: 'Impassive', context: 'Emotion', definition: 'Not feeling or showing emotion.', example: 'He kept an impassive face during the trial.' },
      { word: 'Impede', context: 'General', definition: 'To delay or prevent someone or something by obstructing them.', example: 'Fallen trees impede the rescue efforts.' },
      { word: 'Impermeable', context: 'Science', definition: 'Not allowing fluid to pass through.', example: 'The rain jacket is made of impermeable material.' },
      { word: 'Imperturbable', context: 'Emotion', definition: 'Unable to be upset or excited; calm.', example: 'The pilot’s imperturbable nature saved many lives.' },
      { word: 'Impervious', context: 'Physical/Emotional', definition: 'Not allowing something to enter; unable to be affected by.', example: 'He was impervious to criticism; he just didn\'t care what they said.' },
      { word: 'Implacable', context: 'Emotion', definition: 'Unable to be appeased or calmed down.', example: 'He had an implacable hatred for his enemy.' },
      { word: 'Implicit', context: 'Logic', definition: 'Suggested though not directly expressed.', example: 'She interpreted his nod as an implicit agreement.' },
      { word: 'Implode', context: 'Physical', definition: 'To collapse or cause to collapse violently inwards.', example: 'The old building was scheduled to implode.' },
      { word: 'Inadvertently', context: 'Action', definition: 'Without intention; accidentally.', example: 'I inadvertently deleted the file.' },
      { word: 'Inchoate', context: 'Development', definition: 'Just begun and so not fully formed or developed.', example: 'He had an inchoate idea for a novel, but no plot yet.' },
      { word: 'Incongruity', context: 'Logic', definition: 'The state of being out of place or not fitting.', example: 'The incongruity of a clown at a funeral was striking.' },
      { word: 'Inconsequential', context: 'General', definition: 'Not important or significant.', example: 'His remarks were seen as inconsequential.' },
      { word: 'Incorporate', context: 'General', definition: 'To take in or contain something as part of a whole.', example: 'The design incorporates traditional elements.' },
      { word: 'Indeterminate', context: 'Logic', definition: 'Not exactly known, established, or defined.', example: 'The date of the event is still indeterminate.' },
      { word: 'Indigence', context: 'Money', definition: 'Extreme poverty.', example: 'He lived in a state of indigence.' },
      { word: 'Indolent', context: 'Personality', definition: 'Wanting to avoid activity or exertion; lazy.', example: 'The indolent student failed all his classes.' },
      { word: 'Inert', context: 'Physical', definition: 'Lacking the ability or strength to move.', example: 'The chemical remains inert at room temperature.' },
      { word: 'Ingenuous', context: 'Personality', definition: 'Innocent and unsuspecting.', example: 'His ingenuous nature made him a target for scammers.' },
      { word: 'Inherent', context: 'Nature', definition: 'Existing in something as a permanent, essential, or characteristic attribute.', example: 'Risks are inherent in any business venture.' },
      { word: 'Innocuous', context: 'General', definition: 'Not harmful or offensive.', example: 'The spider is innocuous.' },
      { word: 'Insensible', context: 'Physical', definition: "Without one's mental faculties (unconscious) or unaware of.", example: 'He was insensible to the danger.' },
      { word: 'Insinuate', context: 'Speech', definition: 'To suggest or hint something bad in an indirect and unpleasant way.', example: 'Are you insinuating that I cheated?' },
      { word: 'Insipid', context: 'Food/Personality', definition: 'Lacking flavor or interest.', example: 'The movie was so insipid I fell asleep in ten minutes.' },
      { word: 'Insularity', context: 'Attitude', definition: "Ignorance of or lack of interest in cultures, ideas, or peoples outside one's own experience.", nuance: 'Being "narrow-minded" or "closed off."', example: 'The village was known for its insularity.' },
      { word: 'Intractable', context: 'Problems/People', definition: 'Hard to control or deal with.', example: 'The problem of poverty is intractable.' },
      { word: 'Intransigence', context: 'Attitude', definition: 'Refusal to change one\'s views or to agree about something.', example: 'The negotiations failed due to the diplomat’s intransigence.' },
      { word: 'Inundate', context: 'Physical/Task', definition: 'To overwhelm someone with things or people to be dealt with; to flood.', example: 'The office was inundated with calls.' },
      { word: 'Inured', context: 'Experience', definition: 'Accustomed to something, especially something unpleasant.', example: 'After years of living in the city, she was inured to the noise of sirens.' },
      { word: 'Invective', context: 'Speech', definition: 'Insulting, abusive, or highly critical language.', example: 'He unleashed a torrent of invective.' },
      { word: 'Irascible', context: 'Personality', definition: 'Having or showing a tendency to be easily angered.', example: 'The irascible professor shouted at his students.' },
      { word: 'Irresolute', context: 'Personality', definition: 'Showing or feeling hesitancy; uncertain.', example: 'He stood irresolute at the crossroads.' },
      { word: 'Itinerary', context: 'General', definition: 'A planned route or journey.', example: 'We have a busy itinerary for our trip.' }
    ]
  },
  {
    id: 'block7',
    title: 'Block 7: L – M',
    words: [
      { word: 'Laconic', context: 'Speech', definition: 'Using very few words.', example: 'The cowboy was known for his laconic style.' },
      { word: 'Lassitude', context: 'Physical', definition: 'A state of physical or mental weariness; lack of energy.', example: 'A feeling of lassitude overcame her after the long hike.' },
      { word: 'Latent', context: 'Science/Personality', definition: 'Existing but not yet developed or manifest; hidden or concealed.', example: 'He has a latent talent for music that he hasn\'t discovered yet.' },
      { word: 'Laud', context: 'General', definition: 'To praise highly.', example: 'The hero was lauded for his bravery.' },
      { word: 'Lethargic', context: 'Physical', definition: 'Affected by lethargy; sluggish and apathetic.', example: 'I felt lethargic after the big meal.' },
      { word: 'Levee', context: 'General', definition: 'An embankment built to prevent the overflow of a river.', example: 'The levee protects the city from floods.' },
      { word: 'Levity', context: 'Social', definition: 'Humor or frivolity, especially the treatment of a serious matter with humor or in a manner lacking due respect.', example: 'She tried to inject some levity into the tense situation.' },
      { word: 'Log', context: 'General', definition: 'An official record of events during a particular period.', example: 'The captain kept a meticulous log of the voyage.' },
      { word: 'Loquacious', context: 'Personality', definition: 'Tending to talk a great deal; talkative.', example: 'The loquacious salesman kept me talking for an hour.' },
      { word: 'Lucid', context: 'Communication', definition: 'Expressed clearly; easy to understand.', example: 'The instructions were lucid and easy to follow.' },
      { word: 'Luminous', context: 'General', definition: 'Full of or shedding light; bright or shining, especially in the dark.', example: 'The moon was luminous in the clear sky.' },
      { word: 'Magnanimity', context: 'Character', definition: 'The virtue of being generous in forgiving an insult or injury.', example: 'He showed great magnanimity by forgiving his rival.' },
      { word: 'Malingerer', context: 'Action', definition: 'A person who exaggerates or feigns illness in order to escape duty or work.', example: 'The boss suspected him of being a malingerer.' },
      { word: 'Malleable', context: 'Physical/Personality', definition: 'Easily influenced; pliable.', example: 'Gold is a very malleable metal.' },
      { word: 'Maverick', context: 'Personality', definition: 'An unorthodox or independent-minded person.', example: 'He is a true maverick who refuses to follow the rules.' },
      { word: 'Mendacious', context: 'Personality', definition: 'Not telling the truth; lying.', example: 'The witness gave mendacious testimony.' },
      { word: 'Metamorphosis', context: 'Science/Life', definition: 'A change of the form or nature of a thing or person into a completely different one.', example: 'The caterpillar undergoes a complete metamorphosis into a butterfly.' },
      { word: 'Meticulous', context: 'Action', definition: 'Showing great attention to detail; very careful and precise.', example: 'She is meticulous about her work.' },
      { word: 'Misanthrope', context: 'Personality', definition: 'A person who dislikes humankind and avoids human society.', example: 'The misanthrope lived alone in the woods.' },
      { word: 'Mitigate', context: 'Situation', definition: 'To make less severe, serious, or painful.', example: 'The new law aims to mitigate the effects of poverty.' },
      { word: 'Mollify', context: 'Emotion', definition: 'To appease the anger or anxiety of someone.', example: 'He tried to mollify his angry boss.' },
      { word: 'Morose', context: 'Emotion', definition: 'Sullen and ill-tempered.', example: 'He was morose after his team lost the game.' },
      { word: 'Mundane', context: 'Life', definition: 'Lacking interest or excitement; dull; of this earthly world.', example: 'He couldn\'t stand the mundane tasks of his office job.' }
    ]
  },
  {
    id: 'block8',
    title: 'Block 8: N – P',
    words: [
      { word: 'Negate', context: 'General', definition: 'To nullify; make ineffective.', example: 'Alcohol can negate the effects of the medicine.' },
      { word: 'Neophyte', context: 'Status', definition: 'A person who is new to a subject, skill, or belief.', example: 'As a neophyte in the kitchen, I kept burning my meals.' },
      { word: 'Obdurate', context: 'Personality', definition: 'Stubbornly refusing to change one\'s opinion or course of action.', example: 'He remained obdurate, refusing to admit he was wrong.' },
      { word: 'Obsequious', context: 'Social', definition: 'Obedient or attentive to an excessive or servile degree.', example: 'The obsequious waiter kept refilling our glasses every minute.' },
      { word: 'Obviate', context: 'Action', definition: 'To remove a need or difficulty.', example: 'The new medical treatment obviated the need for surgery.' },
      { word: 'Occlude', context: 'Science/Physical', definition: 'To stop, close up, or obstruct.', example: 'The blood clot can occlude the artery.' },
      { word: 'Officious', context: 'Personality', definition: 'Assertive of authority in an annoyingly domineering way, especially with regard to petty or trivial matters.', example: 'The officious office manager kept telling everyone how to do their jobs.' },
      { word: 'Onerous', context: 'Task', definition: 'Involving an amount of effort and difficulty that is oppressively burdensome.', example: 'The project proved to be much more onerous than we expected.' },
      { word: 'Oscillate', context: 'General', definition: 'To move or swing back and forth at a regular speed.', example: 'The fan oscillates to cool the whole room.' },
      { word: 'Ostentatious', context: 'Style', definition: 'Characterized by vulgar or pretentious display; designed to impress or attract notice.', example: 'He drives an ostentatious sports car.' },
      { word: 'Paragon', context: 'Social', definition: 'A person or thing viewed as a model of excellence.', example: 'She is a paragon of virtue.' },
      { word: 'Partisan', context: 'Politics', definition: 'A strong supporter of a party, cause, or person.', example: 'The newspaper is known for its partisan views.' },
      { word: 'Pathological', context: 'Science', definition: 'Involving, caused by, or of the nature of a physical or mental disease.', example: 'He is a pathological liar.' },
      { word: 'Paucity', context: 'Quantity', definition: 'The presence of something only in small or insufficient quantities or amounts; scarcity.', example: 'There is a paucity of evidence for his claims.' },
      { word: 'Pedantic', context: 'Education', definition: 'Excessively concerned with minor details and rules or with displaying academic learning.', example: 'The pedantic teacher spent half the class correcting our spelling.' },
      { word: 'Penchant', context: 'Personality', definition: 'A strong or habitual liking for something or tendency to do something.', example: 'He has a penchant for expensive watches.' },
      { word: 'Penury', context: 'Money', definition: 'Extreme poverty; destitution.', example: 'He died in penury.' },
      { word: 'Perennial', context: 'Time', definition: 'Lasting or existing for a long or apparently infinite time.', example: 'The problem of traffic is a perennial one in this city.' },
      { word: 'Perfidious', context: 'Character', definition: 'Deceitful and untrustworthy.', example: 'The king was betrayed by his perfidious advisors.' },
      { word: 'Perfunctory', context: 'Action', definition: 'Carried out with a minimum of effort or reflection.', nuance: 'Doing something just because you have to, with no heart in it.', example: 'She gave a perfunctory nod as she walked past.' },
      { word: 'Permeable', context: 'Science', definition: 'Allowing liquids or gases to pass through it.', example: 'Clay is not very permeable to water.' },
      { word: 'Pervasive', context: 'Situation', definition: 'Spreading widely throughout an area or a group of people.', example: 'The smell of coffee was pervasive in the house.' },
      { word: 'Phlegmatic', context: 'Personality', definition: 'Having an unemotional and stolidly calm disposition.', example: 'The doctor remained phlegmatic even when faced with an emergency.' },
      { word: 'Piety', context: 'Religion/Social', definition: 'The quality of being religious or reverent.', example: 'Acts of piety are important in many religions.' },
      { word: 'Placate', context: 'Emotion', definition: 'To make someone less angry or hostile.', example: 'He tried to placate his angry neighbor with a bottle of wine.' },
      { word: 'Plasticity', context: 'Science', definition: 'The quality of being easily shaped or molded.', example: 'The brain exhibits a high degree of plasticity.' },
      { word: 'Platitude', context: 'Speech', definition: 'A remark or statement, especially one with a moral content, that has been used too often to be interesting or thoughtful.', example: 'The commencement speaker was full of platitudes.' },
      { word: 'Plethora', context: 'Quantity', definition: 'A large or excessive amount of something.', example: 'We have a plethora of choices for dinner.' },
      { word: 'Plummet', context: 'General', definition: 'To fall or drop straight down at high speed.', example: 'Stock prices plummeted after the news.' },
      { word: 'Porous', context: 'Science', definition: 'Having minute spaces or holes through which liquid or air may pass.', example: 'The sponge is very porous.' },
      { word: 'Pragmatic', context: 'Philosophy', definition: 'Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.', example: 'We need a pragmatic approach to solve this problem.' },
      { word: 'Preamble', context: 'Speech', definition: 'An introduction to a speech or piece of writing.', example: 'The Preamble to the Constitution defines its purpose.' },
      { word: 'Precarious', context: 'Situation', definition: 'Not securely held or in position; dangerously likely to fall or collapse.', example: 'The ladder felt precarious on the uneven ground.' },
      { word: 'Precipitate', context: 'Action', definition: 'To cause an event or situation (typically one that is bad) to happen suddenly, unexpectedly, or prematurely.', example: 'The incident precipitated a full-scale crisis.' },
      { word: 'Precursor', context: 'Science/History', definition: 'A person or thing that comes before another of the same kind; a forerunner.', example: 'The rotary phone was the precursor to the smartphone.' },
      { word: 'Presumptuous', context: 'Social', definition: 'Failing to observe the limits of what is permitted or appropriate.', example: 'It was presumptuous of him to assume he was invited.' },
      { word: 'Prevaricate', context: 'Speech', definition: 'To speak or act in an evasive way (lying).', example: 'Stop prevaricating and tell me the truth!' },
      { word: 'Pristine', context: 'General', definition: 'In its original condition; unspoiled.', example: 'The beach was in pristine condition.' },
      { word: 'Probity', context: 'Character', definition: 'The quality of having strong moral principles; honesty and decency.', example: 'His probity was never questioned.' },
      { word: 'Problematic', context: 'General', definition: 'Constituting or presenting a problem or difficulty.', example: 'The new rules are problematic for many businesses.' },
      { word: 'Prodigal', context: 'Money', definition: 'Spending money or resources freely and recklessly; wastefully extravagant.', example: 'The prodigal son wasted all his inheritance.' },
      { word: 'Profound', context: 'Logic/Feeling', definition: 'Very great or intense; having or showing great knowledge or insight.', example: 'The discovery had a profound effect on the field of medicine.' },
      { word: 'Prohibitive', context: 'Money', definition: '(Of a price or charge) excessively high.', example: 'The cost of living in the city is prohibitive for many.' },
      { word: 'Proliferate', context: 'General', definition: 'To increase rapidly in numbers; multiply.', example: 'Information can proliferate quickly on the internet.' },
      { word: 'Propensity', context: 'Personality', definition: 'An inclination or natural tendency to behave in a particular way.', example: 'He has a propensity for getting into trouble.' },
      { word: 'Propitiate', context: 'Religion/Conflict', definition: 'To win or regain the favor of a god, spirit, or person by doing something that pleases them.', example: 'They offered sacrifices to propitiate the gods.' },
      { word: 'Propriety', context: 'Social', definition: 'The state or quality of conforming to conventionally accepted standards of behavior or morals.', example: 'She always behaves with great propriety.' },
      { word: 'Proscribe', context: 'Law', definition: 'To forbid, especially by law.', example: 'Smoking is proscribed in all public buildings.' },
      { word: 'Pungent', context: 'General', definition: 'Having a sharply strong taste or smell.', example: 'The smell of onions is very pungent.' }
    ]
  },
  {
    id: 'block9',
    title: 'Block 9: Q – S',
    words: [
      { word: 'Qualified', context: 'Logic', definition: 'Not absolute; limited or conditional.', nuance: '"I like it, but only with certain conditions."', example: 'He gave his qualified support for the new policy.' },
      { word: 'Quibble', context: 'Speech', definition: 'A slight objection or criticism about a trivial matter.', example: 'Let\'s not quibble over small details.' },
      { word: 'Quiescent', context: 'Science', definition: 'In a state or period of inactivity or dormancy.', example: 'The volcano is in a quiescent phase.' },
      { word: 'Rarefied', context: 'Social/Physical', definition: 'Distant from the lives and concerns of ordinary people; (of air) lower pressure.', example: 'The rarefied atmosphere of the elite club.' },
      { word: 'Recalcitrant', context: 'Personality', definition: 'Having an obstinately uncooperative attitude toward authority or discipline.', example: 'The recalcitrant student refused to follow instructions.' },
      { word: 'Recant', context: 'Beliefs', definition: 'To say that one no longer holds an opinion or belief, especially one considered heretical.', example: 'Galileo was forced to recant his views.' },
      { word: 'Recluse', context: 'Personality', definition: 'A person who lives a solitary life and tends to avoid other people.', example: 'He became a recluse after the death of his wife.' },
      { word: 'Recondite', context: 'Knowledge', definition: 'Little known; abstruse (hard to understand).', example: 'The book is full of recondite information.' },
      { word: 'Refractory', context: 'Personality/Science', definition: 'Stubborn or unmanageable; resistant to a process or stimulus.', example: 'The refractory horse refused to move.' },
      { word: 'Refute', context: 'Logic', definition: 'To prove a statement or theory to be wrong or false.', example: 'New evidence served to refute her theory.' },
      { word: 'Relegate', context: 'Status', definition: 'To dismiss to an inferior rank or position.', example: 'The team was relegated to the smaller league.' },
      { word: 'Reproach', context: 'Social', definition: 'To address someone in such a way as to express disapproval or disappointment.', example: 'His mother’s reproachful look was enough to make him feel guilty.' },
      { word: 'Reprobate', context: 'Character', definition: 'An unprincipled person (often used humorously).', example: 'The old reprobate was back at his usual tricks.' },
      { word: 'Repudiate', context: 'Logic', definition: 'To refuse to accept or be associated with.', example: 'The government repudiated the old treaty.' },
      { word: 'Rescind', context: 'Law', definition: 'To revoke, cancel, or repeal a law, order, or agreement.', example: 'The company decided to rescind the job offer.' },
      { word: 'Resolution', context: 'General', definition: 'A firm decision to do or not to do something.', example: 'He made a New Year’s resolution to exercise more.' },
      { word: 'Resolve', context: 'General', definition: 'To settle or find a solution to a problem.', example: 'They were able to resolve their differences.' },
      { word: 'Reticent', context: 'Personality', definition: 'Not revealing one\'s thoughts or feelings readily.', example: 'She is reticent about her personal life.' },
      { word: 'Reverent', context: 'General', definition: 'Feeling or showing deep and solemn respect.', example: 'The crowd stood in reverent silence.' },
      { word: 'Sage', context: 'Status', definition: 'A profoundly wise man.', example: 'The villagers sought advice from the old sage.' },
      { word: 'Salubrious', context: 'Health', definition: 'Health-giving; healthy.', example: 'The mountain air is very salubrious.' },
      { word: 'Sanction', context: 'Law', definition: 'A threatened penalty for disobeying a law OR official permission or approval.', example: 'The UN imposed sanctions on the country.' },
      { word: 'Satiate', context: 'General', definition: 'To satisfied a desire or an appetite to the full.', example: 'A huge meal was enough to satiate his hunger.' },
      { word: 'Saturate', context: 'General', definition: 'To cause something to become thoroughly soaked with liquid so that no more can be absorbed.', example: 'The rain completely saturated the ground.' },
      { word: 'Savor', context: 'General', definition: 'To enjoy or appreciate something pleasant completely, especially by dwelling on it.', example: 'I wanted to savor every moment of my vacation.' },
      { word: 'Secrete', context: 'Biology', definition: '(Of a cell, gland, or organ) to produce and discharge a substance.', example: 'Glands in the mouth secrete saliva.' },
      { word: 'Shard', context: 'General', definition: 'A piece of broken ceramic, metal, glass, or rock, typically having sharp edges.', example: 'Shards of glass were scattered on the floor.' },
      { word: 'Skeptical', context: 'General', definition: 'Inclined to question or doubt all accepted opinions.', example: 'I’m skeptical about his ability to do the job.' },
      { word: 'Soporific', context: 'Science/Speech', definition: 'Tending to induce drowsiness or sleep.', example: 'The hum of the machine had a soporific effect.' },
      { word: 'Specious', context: 'Logic', definition: 'Plausible but wrong.', nuance: 'An argument that sounds right but is actually a lie.', example: 'He made a specious argument that was easy to dismantle.' },
      { word: 'Spectrum', context: 'General', definition: 'Used to classify something in terms of its position on a scale between two extreme points.', example: 'There is a whole spectrum of political opinions.' },
      { word: 'Sporadic', context: 'General', definition: 'Occurring at irregular intervals or only in a few places; scattered or isolated.', example: 'The fighting was sporadic across the country.' },
      { word: 'Stigma', context: 'General', definition: 'A mark of disgrace associated with a particular circumstance, quality, or person.', example: 'There is a social stigma attached to mental illness.' },
      { word: 'Stint', context: 'Work', definition: 'Supply an ungenerous or inadequate amount of something; a period of work.', example: 'He did a two-year stint in the army.' },
      { word: 'Stipulate', context: 'Law', definition: 'To demand or specify a requirement, typically as part of a bargain or agreement.', example: 'The contract stipulates that the work must be finished by June.' },
      { word: 'Stolid', context: 'Personality', definition: 'Calm, dependable, and showing little emotion or animation.', example: 'He is a stolid man who never gets excited.' },
      { word: 'Strut', context: 'General', definition: 'To walk with a stiff, erect, and apparently arrogant or conceited gait.', example: 'The peacock struts around the garden.' },
      { word: 'Subpoena', context: 'Law', definition: 'A writ ordering a person to attend a court.', example: 'He was served a subpoena to testify.' },
      { word: 'Subside', context: 'General', definition: 'To become less intense, violent, or severe.', example: 'The storm eventually subsided.' },
      { word: 'Substantiate', context: 'General', definition: 'To provide evidence to support or prove the truth of.', example: 'We have enough evidence to substantiate our claim.' },
      { word: 'Supersede', context: 'General', definition: 'To take the place of a person or thing previously in authority or use.', example: 'The new rules supersede the old ones.' },
      { word: 'Supposition', context: 'General', definition: 'A belief held without proof or certain knowledge; an assumption or hypothesis.', example: 'His theory is based on pure supposition.' }
    ]
  },
  {
    id: 'block10',
    title: 'Block 10: T – Z',
    words: [
      { word: 'Tacit', context: 'Communication', definition: 'Understood or implied without being stated.', example: 'Their silence was interpreted as tacit agreement.' },
      { word: 'Tangential', context: 'Logic', definition: 'Relating to a subject only irrelevant or in a very slight way.', example: 'His comments were tangential to the main discussion.' },
      { word: 'Tenuous', context: 'Logic', definition: 'Very weak or slight.', example: 'The evidence for his claim is very tenuous.' },
      { word: 'Tirade', context: 'Speech', definition: 'A long, angry speech of criticism or accusation.', example: 'The boss launched into a tirade against his staff.' },
      { word: 'Torpor', context: 'Physical', definition: 'A state of physical or mental inactivity; lethargy.', example: 'He fell into a state of torpor.' },
      { word: 'Tortuous', context: 'Path/Logic', definition: 'Full of twists and turns; excessively lengthy and complex.', example: 'The road up the mountain is very tortuous.' },
      { word: 'Tractable', context: 'Personality', definition: '(Of a person or animal) easy to control or influence.', example: 'The group of students proved to be very tractable.' },
      { word: 'Transgression', context: 'Law/Morals', definition: 'An act that goes against a law, rule, or code of conduct; an offense.', example: 'His transgression resulted in his expulsion.' },
      { word: 'Truculence', context: 'Personality', definition: 'Eager or quick to argue or fight; aggressively defiant.', example: 'His truculence made it hard for him to keep a job.' },
      { word: 'Vacillate', context: 'Personality', definition: 'To alternate or waver between different opinions or actions; be indecisive.', example: 'He vacillated between wanting the red car and the blue one.' },
      { word: 'Venerate', context: 'General', definition: 'To regard with great respect; revere.', example: 'The old master was venerated by his students.' },
      { word: 'Veracious', context: 'Personality', definition: 'Speaking or representing the truth.', example: 'He is a veracious witness.' },
      { word: 'Verbose', context: 'Speech', definition: 'Using or expressed in more words than are needed.', example: 'The essay was so verbose it was hard to find the main point.' },
      { word: 'Viable', context: 'Science/Business', definition: 'Capable of working successfully; feasible.', example: 'The project is no longer viable.' },
      { word: 'Viscous', context: 'Science', definition: 'Having a thick, sticky consistency between solid and liquid.', example: 'Honey is a viscous liquid.' },
      { word: 'Vituperative', context: 'Speech', definition: 'Bitter and abusive.', example: 'The vituperative attack on his character was unfair.' },
      { word: 'Volatile', context: 'Science/Situation', definition: 'Liable to change rapidly and unpredictably, especially for the worse.', example: 'The political situation remained volatile.' },
      { word: 'Wary', context: 'General', definition: 'Feeling or showing caution about possible dangers or problems.', example: 'Be wary of offers that seem too good to be true.' },
      { word: 'Welter', context: 'Quantity', definition: 'A large number of items in no order; a confused mass.', example: 'The room was a welter of books and papers.' },
      { word: 'Whimsical', context: 'Personality', definition: 'Playfully quaint or fanciful, especially in an appealing and amusing way.', example: 'She has a whimsical sense of humor.' },
      { word: 'Zealot', context: 'Politics/Religion', definition: 'A person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals.', example: 'The religious zealot dedicated his life to his beliefs.' }
    ]
  }
];
